#!/usr/bin/env lua
-- gen_tokens.lua -- single-source token generator for the AIODI design system.
--
-- aiodi.lua is the ONE source of truth for the AIODI palette/spacing/radius/type
-- scale. This script requires it and emits two DERIVED artifacts so the voice-UI
-- prompt, the deterministic linter, and the web settings UI never drift from the
-- on-device tokens:
--   * components/lua_modules/lua_module_lvgl/src/aiodi_tokens.h
--       C macros (palette prompt fragment + linter palette) consumed byte-identically
--       by odk_voice_ui.c (device) and sim_voice_ui.c (sim).
--   * application/open_deskos/components/http_server/frontend_source/src/aiodi_tokens.css
--       CSS custom properties for the SolidJS settings UI (base tokens only; the web
--       keeps its intentional overrides in index.css).
--
-- Run from research/esp32-p4-c6-deskos/firmware/ after editing aiodi.lua:
--   lua scripts/gen_tokens.lua
-- Generated files are checked in so builds never depend on a Lua interpreter.

-- Stub lvgl: we only read aiodi's token tables, never build widgets.
package.loaded.lvgl = setmetatable({}, { __index = function() return function() end end })

local LIB = "components/lua_modules/lua_module_lvgl/lib"
package.path = LIB .. "/?.lua;" .. package.path

local aiodi = require("aiodi")

-- Presentation order for the prompt. Values come from aiodi.colors; if a color is
-- added there, add its key to a group here so it reaches the prompt + linter.
local COLOR_GROUPS = {
    { "bg", "surface", "elevated", "button" },
    { "stroke", "stroke_focus", "primary", "secondary" },
    { "red", "green", "blue" },
}
local SPACE_ORDER  = { "xs", "sm", "md", "lg", "xl" }
local RADIUS_ORDER = { "sm", "md", "lg", "pill" }
local TEXT_ORDER   = { "caption", "body", "title", "display", "mega" }

local function kv_line(prefix, order, tbl)
    local parts = {}
    for _, k in ipairs(order) do parts[#parts + 1] = k .. "=" .. tostring(tbl[k]) end
    return prefix .. table.concat(parts, " ")
end

-- One C string literal for a logical prompt line, with trailing \n.
local function cstr(s) return '"' .. s .. '\\n"' end

local function build_header()
    -- AIODI_PROMPT_COLORS: 3 source lines, C-continued.
    local color_lines = {}
    for i, group in ipairs(COLOR_GROUPS) do
        local prefix = (i == 1) and "  aiodi.colors: " or "    "
        color_lines[#color_lines + 1] = cstr(kv_line(prefix, group, aiodi.colors))
    end
    local colors_macro = table.concat(color_lines, " \\\n    ")

    -- AIODI_LINTER_PALETTE: unique hex values (lowercase, no '#'), first-seen order.
    local seen, items = {}, {}
    for _, group in ipairs(COLOR_GROUPS) do
        for _, k in ipairs(group) do
            local v = aiodi.colors[k]:sub(2):lower()
            if not seen[v] then seen[v] = true; items[#items + 1] = '"' .. v .. '"' end
        end
    end
    items[#items + 1] = "NULL"
    local linter_macro = "    " .. table.concat(items, ", ")

    return table.concat({
        "/*",
        " * aiodi_tokens.h -- GENERATED by scripts/gen_tokens.lua from aiodi.lua.",
        " * Do not edit by hand; re-run the generator after changing aiodi.lua tokens.",
        " *",
        " * Single source for the voice-UI prompt palette + the deterministic linter's",
        " * whitelist, shared byte-identically by odk_voice_ui.c (device) and",
        " * sim_voice_ui.c (sim).",
        " */",
        "#ifndef AIODI_TOKENS_H",
        "#define AIODI_TOKENS_H",
        "",
        "/* aiodi.colors / .space / .radius / .text, formatted for the voice-UI system",
        " * prompt. C adjacent-string-literal concatenation joins these into the prompt. */",
        "#define AIODI_PROMPT_COLORS \\",
        "    " .. colors_macro,
        "",
        "#define AIODI_PROMPT_SPACE  " .. cstr(kv_line("  aiodi.space:  ", SPACE_ORDER, aiodi.space)),
        "#define AIODI_PROMPT_RADIUS " .. cstr(kv_line("  aiodi.radius: ", RADIUS_ORDER, aiodi.radius)),
        "#define AIODI_PROMPT_TEXT   " .. cstr(kv_line("  aiodi.text:   ", TEXT_ORDER, aiodi.text)),
        "",
        "/* Linter palette: every legal '#rrggbb' (lowercase, no '#') in aiodi.colors.",
        " * Use as:  static const char *palette[] = { AIODI_LINTER_PALETTE }; */",
        "#define AIODI_LINTER_PALETTE \\",
        linter_macro,
        "",
        "#endif /* AIODI_TOKENS_H */",
        "",
    }, "\n")
end

local function build_css()
    local lines = {
        "/*",
        " * aiodi_tokens.css -- GENERATED by scripts/gen_tokens.lua from aiodi.lua.",
        " * Do not edit by hand. AIODI base tokens as CSS custom properties for the",
        " * SolidJS settings UI. The web UI keeps its own intentional overrides",
        " * (bg lifted off pure black, text-secondary) in index.css and references",
        " * these base tokens there.",
        " */",
        ":root {",
    }
    for _, group in ipairs(COLOR_GROUPS) do
        for _, k in ipairs(group) do
            lines[#lines + 1] = string.format("  --aiodi-color-%s: %s;", k, aiodi.colors[k])
        end
    end
    for _, k in ipairs(SPACE_ORDER) do
        lines[#lines + 1] = string.format("  --aiodi-space-%s: %dpx;", k, aiodi.space[k])
    end
    for _, k in ipairs(RADIUS_ORDER) do
        local v = aiodi.radius[k]
        lines[#lines + 1] = string.format("  --aiodi-radius-%s: %s;", k, v == 999 and "999px" or v .. "px")
    end
    lines[#lines + 1] = "}"
    return table.concat(lines, "\n") .. "\n"
end

local OUT_H   = "components/lua_modules/lua_module_lvgl/src/aiodi_tokens.h"
local OUT_CSS = "application/open_deskos/components/http_server/frontend_source/src/aiodi_tokens.css"

local function write(path, content)
    local f = assert(io.open(path, "w"))
    f:write(content)
    f:close()
    print(string.format("  wrote %s (%d bytes)", path, #content))
end

print("gen_tokens: emitting from aiodi.lua v" .. tostring(aiodi.VERSION))
write(OUT_H, build_header())
write(OUT_CSS, build_css())
print("done.")
