/*
 * aiodi_tokens.h -- GENERATED by scripts/gen_tokens.lua from aiodi.lua.
 * Do not edit by hand; re-run the generator after changing aiodi.lua tokens.
 *
 * Single source for the voice-UI prompt palette + the deterministic linter's
 * whitelist, shared byte-identically by odk_voice_ui.c (device) and
 * sim_voice_ui.c (sim).
 */
#ifndef AIODI_TOKENS_H
#define AIODI_TOKENS_H

/* aiodi.colors / .space / .radius / .text, formatted for the voice-UI system
 * prompt. C adjacent-string-literal concatenation joins these into the prompt. */
#define AIODI_PROMPT_COLORS \
    "  aiodi.colors: bg=#000000 surface=#171717 elevated=#1f1f1f button=#383838\n" \
    "    stroke=#383838 stroke_focus=#b5b5b5 primary=#ffffff secondary=#706f70\n" \
    "    red=#eb5757 green=#34c759 blue=#025bc2\n"

#define AIODI_PROMPT_SPACE  "  aiodi.space:  xs=4 sm=8 md=16 lg=24 xl=40\n"
#define AIODI_PROMPT_RADIUS "  aiodi.radius: sm=8 md=16 lg=24 pill=999\n"
#define AIODI_PROMPT_TEXT   "  aiodi.text:   caption=20 body=28 title=40 display=96 mega=180\n"

/* Linter palette: every legal '#rrggbb' (lowercase, no '#') in aiodi.colors.
 * Use as:  static const char *palette[] = { AIODI_LINTER_PALETTE }; */
#define AIODI_LINTER_PALETTE \
    "000000", "171717", "1f1f1f", "383838", "b5b5b5", "ffffff", "706f70", "eb5757", "34c759", "025bc2", NULL

#endif /* AIODI_TOKENS_H */
