set(LAUNCHER_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/lib/launcher.lua")
set(PAGER_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/lib/core/pager.lua")
set(POMODORO_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/lib/plugins/pomodoro.lua")
set(LAYOUT_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_layout.c")
set(STYLE_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_style.c")
set(EVENTS_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_events.c")
set(PRIVATE_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_private.h")
set(METHODS_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_methods.c")
set(VALUE_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_value.c")
set(EXTRA_WIDGETS_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_extra_widgets.c")
set(CORE_WIDGETS_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_core_widgets.c")
set(INDEV_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_indev.c")
set(RUNTIME_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_runtime.c")
set(TOUCH_QUEUE_SOURCE "${ODK_ROOT}/components/lua_modules/lua_module_lvgl/src/lua_lvgl_touch_sample_queue.h")
set(VOICE_UI_SOURCE "${ODK_ROOT}/application/edge_agent/main/odk_voice_ui.c")
set(DISPLAY_BRINGUP_SOURCE "${ODK_ROOT}/application/edge_agent/main/odk_display_bringup.c")
set(SDKCONFIG_DEFAULTS_SOURCE "${ODK_ROOT}/application/edge_agent/sdkconfig.defaults")
set(BOARD_SDKCONFIG_DEFAULTS_SOURCE "${ODK_ROOT}/application/edge_agent/boards/guition/jc4880p443c/sdkconfig.defaults.board")

foreach(path IN ITEMS "${LAUNCHER_SOURCE}" "${PAGER_SOURCE}" "${POMODORO_SOURCE}" "${LAYOUT_SOURCE}" "${STYLE_SOURCE}" "${EVENTS_SOURCE}" "${PRIVATE_SOURCE}" "${METHODS_SOURCE}" "${VALUE_SOURCE}" "${EXTRA_WIDGETS_SOURCE}" "${CORE_WIDGETS_SOURCE}" "${INDEV_SOURCE}" "${RUNTIME_SOURCE}" "${TOUCH_QUEUE_SOURCE}" "${VOICE_UI_SOURCE}" "${DISPLAY_BRINGUP_SOURCE}" "${SDKCONFIG_DEFAULTS_SOURCE}" "${BOARD_SDKCONFIG_DEFAULTS_SOURCE}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "home pager contract input is missing: ${path}")
    endif()
endforeach()

file(READ "${LAUNCHER_SOURCE}" launcher)
file(READ "${PAGER_SOURCE}" pager)
file(READ "${POMODORO_SOURCE}" pomodoro)
file(READ "${LAYOUT_SOURCE}" layout)
file(READ "${STYLE_SOURCE}" style)
file(READ "${EVENTS_SOURCE}" events)
file(READ "${PRIVATE_SOURCE}" private)
file(READ "${METHODS_SOURCE}" methods)
file(READ "${VALUE_SOURCE}" value)
file(READ "${EXTRA_WIDGETS_SOURCE}" extra_widgets)
file(READ "${CORE_WIDGETS_SOURCE}" core_widgets)
file(READ "${INDEV_SOURCE}" indev)
file(READ "${RUNTIME_SOURCE}" runtime)
file(READ "${TOUCH_QUEUE_SOURCE}" touch_queue)
file(READ "${VOICE_UI_SOURCE}" voice_ui)
file(READ "${DISPLAY_BRINGUP_SOURCE}" display_bringup)
file(READ "${SDKCONFIG_DEFAULTS_SOURCE}" sdkconfig_defaults)
file(READ "${BOARD_SDKCONFIG_DEFAULTS_SOURCE}" board_sdkconfig_defaults)

function(require_pattern source label pattern)
    string(FIND "${source}" "${pattern}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "${label}: missing '${pattern}'")
    endif()
endfunction()

function(forbid_pattern source label pattern)
    string(FIND "${source}" "${pattern}" found)
    if(NOT found EQUAL -1)
        message(FATAL_ERROR "${label}: must not contain '${pattern}'")
    endif()
endfunction()

# LVGL's built-in SCROLL_ONE flag limits a snap gesture to the adjacent
# snappable child. A short, fast flick may use release momentum to select that
# adjacent target. At the P4's observed bitmap-frame cadence (~30 ms), the
# home pager needs 180 ms to expose at least six positions in its non-zero
# settle animation. LVGL can cancel it at its current coordinate when the next
# drag starts, so a reverse gesture continues naturally instead of jumping to
# an endpoint.
require_pattern("${pager}" "home pager one-page policy" "scroll_one = true")
require_pattern("${pager}" "home pager adjacent snap alignment" "snap_x = \"center\"")
require_pattern("${pager}" "home pager supports short fast flicks" "momentum = true")
require_pattern("${pager}" "home pager has six-sample settle duration" "local PAGER_SNAP_SETTLE_MS = 180")
require_pattern("${pager}" "home pager has continuous release snap" "snap_anim_ms = PAGER_SNAP_SETTLE_MS")
forbid_pattern("${pager}" "home pager must not jump at release" "snap_anim_ms = 0")

require_pattern("${indev}" "pager flick has bounded prediction" "lv_indev_set_scroll_throw(indev, 15)")
require_pattern("${core_widgets}" "decorative arcs forward horizontal pager drags" "lv_obj_add_flag(obj, LV_OBJ_FLAG_SCROLL_CHAIN_HOR);")

# Lua must expose SCROLL_ONE rather than encoding the policy in a page-count
# specific workaround, so future snap pagers receive the same LVGL guarantee.
require_pattern("${layout}" "scroll-one option parsed" "\"scroll_one\"")
require_pattern("${layout}" "scroll-one flag enabled" "LV_OBJ_FLAG_SCROLL_ONE")
require_pattern("${layout}" "snap animation option parsed" "\"snap_anim_ms\"")
require_pattern("${layout}" "snap animation duration applied" "lv_anim_set_duration(anim, record->scroll_snap_anim_ms)")
require_pattern("${layout}" "zero-duration snap selects step path" "if (record->scroll_snap_anim_ms == 0)")
require_pattern("${layout}" "zero-duration snap commits selected endpoint" "lv_anim_set_path_cb(anim, lv_anim_path_step)")
forbid_pattern("${layout}" "zero snap duration must override LVGL default" "record->scroll_snap_anim_ms == 0 ||")
require_pattern("${layout}" "scrollbar-free pager removes unused theme scroll state" "lv_obj_remove_theme(obj, LV_PART_SCROLLBAR | LV_STATE_SCROLLED)")

# Snapshot paging must switch layers synchronously in LVGL's SCROLL_BEGIN
# callback. LVGL emits that event before it applies the first raw drag delta;
# doing it through pages:on("scroll") waits for the Shell event queue and can
# make the first visible drag frame re-render the full live page tree.
require_pattern("${pager}" "native snapshot layer setup" "pager.pages_scroller:set_scroll_snapshot_layers({")
require_pattern("${pager}" "native snapshot setup only after pre-render" "type(pager.pages_scroller.set_scroll_snapshot_layers) == \"function\" then")
require_pattern("${layout}" "native snapshot layer method" "int lua_lvgl_set_scroll_snapshot_layers(lua_State *L)")
require_pattern("${pager}" "native snapshot setup includes page indicators" "page_indicators = {")
require_pattern("${layout}" "native pager interpolates page indicators" "lua_lvgl_update_scroll_snapshot_indicators")
require_pattern("${layout}" "native pager receives scroll events for page indicators" "LV_EVENT_SCROLL, ud->record")
require_pattern("${layout}" "native marker interpolation is layout-free" "lv_obj_set_style_transform_width")
forbid_pattern("${pager}" "Lua must not interpolate page markers per scroll frame" "local function paint_page_progress()")
require_pattern("${private}" "snapshot records native page indicators" "scroll_snapshot_indicators")
require_pattern("${layout}" "snapshot starts in native scroll-begin" "LV_EVENT_SCROLL_BEGIN")
require_pattern("${layout}" "snapshot ends in native scroll-end" "LV_EVENT_SCROLL_END")
require_pattern("${layout}" "snapshot has an explicit drag-only layer state" "static void lua_lvgl_set_scroll_snapshot_drag_layers")
require_pattern("${layout}" "snapshot suppresses live rendering during a drag" "lua_lvgl_set_scroll_snapshot_drag_layers(record);")
require_pattern("${layout}" "drag layer makes live content transparent without layout work" "lv_obj_set_style_opa_layered(live->obj, LV_OPA_TRANSP, LV_PART_MAIN)")
require_pattern("${layout}" "snapshot records moving dynamic overlays" "scroll_snapshot_overlays")
require_pattern("${layout}" "drag layer makes dynamic overlays visible" "lv_obj_set_style_opa_layered(overlay->obj, LV_OPA_COVER, LV_PART_MAIN)")
require_pattern("${layout}" "idle layer hides dynamic overlays" "lv_obj_set_style_opa_layered(overlay->obj, LV_OPA_TRANSP, LV_PART_MAIN)")
require_pattern("${layout}" "settled selected live page is renderer-visible" "lv_obj_set_style_opa_layered(live->obj, LV_OPA_COVER, LV_PART_MAIN);")
require_pattern("${layout}" "settled snapshot is renderer-transparent" "lv_obj_set_style_opa_layered(image->obj, LV_OPA_TRANSP, LV_PART_MAIN)")
require_pattern("${layout}" "snapshot setup enters its idle live state" "lua_lvgl_set_scroll_snapshot_idle_layers(ud->record);")
require_pattern("${style}" "Lua style exposes renderer-only layered opacity" "strcmp(field, \"opa_layered\") == 0")
require_pattern("${style}" "Lua style maps layered opacity to LVGL" "lv_obj_set_style_opa_layered(obj, (lv_opa_t)value, 0)")
require_pattern("${pager}" "idle snapshot holders are renderer-transparent" "img_holder:set_style({ opa_layered = 0 })")
forbid_pattern("${pager}" "snapshot holders must not start hidden" "img_holder:set_style({ hidden = true })")
require_pattern("${pager}" "bitmap page surface stays in the scrolling wrapper" "local wrap = lvgl.container(pages, {")
require_pattern("${pager}" "snapshot holder belongs to the moving bitmap wrapper" "local img_holder = lvgl.container(wrap, {")
require_pattern("${pager}" "bitmap wrappers use fixed pager slots" "x = (i - 1) * pager.page_slot_w")
forbid_pattern("${pager}" "pager bitmap slots must not use flex layout" "pages:set_flex({")
require_pattern("${pager}" "live pages share a fixed pager input overlay" "local input_overlay = lvgl.container(pages, {")
require_pattern("${pager}" "input overlay is excluded from raw child movement" "input_overlay:set_style({ floating = true })")
require_pattern("${pager}" "live page source lives under fixed input overlay" "local slot = lvgl.container(input_overlay, {")
forbid_pattern("${pager}" "live page source must not move inside bitmap wrapper" "local slot = lvgl.container(wrap, {")
require_pattern("${pager}" "dynamic home overlay belongs to the moving wrapper" "pager.page_drag_layers[i] = drag_layer")
require_pattern("${pager}" "native snapshot setup includes dynamic overlays" "overlays = pager.page_drag_layers")
require_pattern("${layout}" "snapshot records its fixed-page pitch" "scroll_snapshot_page_width")
require_pattern("${layout}" "snapshot restores only its selected live page" "lua_lvgl_snapshot_selected_layer(record)")
require_pattern("${layout}" "selected live page becomes the front input target" "lv_obj_move_foreground(live->obj)")
forbid_pattern("${layout}" "pager selection must not toggle a live page hidden flag" "LV_OBJ_FLAG_HIDDEN")
require_pattern("${pager}" "each live page has an input guard beneath its controls" "local input_guard = lvgl.container(slot, {")
require_pattern("${pager}" "gap touches stay on the selected live page" "input_guard:set_clickable(true)")
require_pattern("${pager}" "snapshot refresh has a focused page helper" "function M.refresh_page_snapshot(page_idx)")
require_pattern("${pager}" "snapshot refresh retains the last known-good image until replacement" "local previous = pager.page_snapshots[page_idx]")
forbid_pattern("${pager}" "timer ticks must not schedule full page snapshots" "refresh_selected_page_snapshot(1)")
forbid_pattern("${pager}" "idle loop must not process full page snapshot refreshes" "process_snapshot_refresh()")

# The moving overlay layer is a deliberately shallow, non-interactive surface.
# Recreating the home grid's rounded date/clock/ring tiles here turns each
# bitmap drag frame back into a large software card render. The pager module
# must stay pure mechanics: no grids, no tiles, no app chrome.
require_pattern("${pager}" "dynamic overlay layer belongs to the moving wrapper" "local drag_layer = lvgl.container(wrap, {")
require_pattern("${pager}" "dynamic overlay layer is non-interactive" "drag_layer:set_clickable(false)")
require_pattern("${pager}" "dynamic overlay layer is renderer-transparent at idle" "drag_layer:set_style({ opa_layered = 0 })")
forbid_pattern("${pager}" "dynamic overlay must not construct a grid" "aiodi.grid(")
forbid_pattern("${pager}" "dynamic overlay must not construct rounded tiles" "aiodi.tile(")
forbid_pattern("${pager}" "dynamic overlay must not carry app chrome" "aiodi.card(")
require_pattern("${style}" "Lua style parses fixed-label text alignment" "lua_getfield(L, index, \"text_align\")")
require_pattern("${style}" "Lua style accepts centered text alignment" "strcmp(value, \"center\") == 0")
require_pattern("${style}" "Lua style applies text alignment" "lv_obj_set_style_text_align(obj, align, 0)")
require_pattern("${private}" "arc background angle method declaration" "lua_lvgl_set_arc_bg_angles")
require_pattern("${methods}" "arc background angle method exposed" "{\"set_bg_angles\", lua_lvgl_set_arc_bg_angles}")
require_pattern("${value}" "arc background angle method implementation" "int lua_lvgl_set_arc_bg_angles(lua_State *L)")
require_pattern("${value}" "arc background angle method updates in place" "lv_arc_set_bg_angles(obj,")
require_pattern("${layout}" "snapshot tracks an in-flight release snap" "scroll_snapshot_snap_active")
require_pattern("${layout}" "snapshot recognizes a release animation event" "lv_event_get_param(event) != NULL")
require_pattern("${layout}" "snapshot retains bitmap layers through input release" "record->scroll_snapshot_snap_active && lv_event_get_param(event) != NULL")
require_pattern("${layout}" "new drag explicitly cancels an old release snap" "lv_obj_stop_scroll_anim(record->obj)")
require_pattern("${layout}" "replacement snap tracks the old animation end" "scroll_snapshot_replacement_pending")
require_pattern("${layout}" "replacement snap confirms it started before clearing pending state" "lua_lvgl_scroll_snapshot_replacement_started_cb")
require_pattern("${layout}" "replacement snap start callback owns pager state" "lv_anim_set_start_cb(anim, lua_lvgl_scroll_snapshot_replacement_started_cb)")
require_pattern("${layout}" "scroll_to prepares snapshot replacement before old animation deletion" "lua_lvgl_prepare_scroll_snapshot_replacement")
require_pattern("${layout}" "scroll_to records replacement preparation" "replacement_prepared = lua_lvgl_prepare_scroll_snapshot_replacement(")
require_pattern("${layout}" "scroll_to passes current target to replacement preparation" "ud->record, obj, x, y, anim);")
require_pattern("${layout}" "scroll_to finalizes a no-op replacement" "replacement_prepared && !lv_obj_is_scrolling(obj)")
require_pattern("${layout}" "scroll_to emits one final end after a no-op replacement" "lv_obj_send_event(obj, LV_EVENT_SCROLL_END, NULL);")
forbid_pattern("${layout}" "no-op replacement must mark before deleting its predecessor" "if (x == lv_obj_get_scroll_x(obj) && y == lv_obj_get_scroll_y(obj))")
require_pattern("${events}" "early snapshot release does not queue Lua scroll-end work" "sub->code != LV_EVENT_SCROLL_END")
require_pattern("${events}" "Lua scroll-end waits for final animation completion" "record->scroll_snapshot_snap_active && lv_event_get_param(event) != NULL")
require_pattern("${events}" "interrupted snap does not queue a stale Lua scroll-end" "record->scroll_snapshot_restarting")
require_pattern("${events}" "superseded snap does not queue a stale Lua scroll-end" "record->scroll_snapshot_replacement_pending")
require_pattern("${layout}" "native scroll begin starts pager trace" "lua_lvgl_indev_trace_pager_scroll_begin_locked")
require_pattern("${layout}" "native scroll end completes pager trace" "lua_lvgl_indev_trace_pager_scroll_end_locked")
require_pattern("${private}" "snapshot layer record storage" "scroll_snapshot_layer_count")
require_pattern("${private}" "snapshot release snap state" "scroll_snapshot_snap_active")
require_pattern("${private}" "snapshot layer method declaration" "lua_lvgl_set_scroll_snapshot_layers")
require_pattern("${methods}" "snapshot layer method exposed" "set_scroll_snapshot_layers")
require_pattern("${extra_widgets}" "snapshot source is written back for PPA" "lua_lvgl_snapshot_sync_for_ppa")
require_pattern("${extra_widgets}" "snapshot PPA writeback uses cache C2M" "ESP_CACHE_MSYNC_FLAG_DIR_C2M")
require_pattern("${extra_widgets}" "snapshot PPA writeback permits partial cache lines" "ESP_CACHE_MSYNC_FLAG_UNALIGNED")
forbid_pattern("${pager}" "legacy Lua snapshot-enter callback" "local function snapshot_pages_for_scroll()")
forbid_pattern("${pager}" "legacy Lua snapshot-restore callback" "local function restore_pages_after_scroll()")
forbid_pattern("${pager}" "native pager movement must not wait for Lua scroll dispatch" "pages:on(\"scroll\", on_home_scroll)")
require_pattern("${pager}" "pager indicators update after native settle" "pages:on(\"scroll_end\", function()")
require_pattern("${pomodoro}" "Pomodoro peek caches its displayed countdown" "local face_value = pomo_mmss(pomo_sync(st))")
require_pattern("${pomodoro}" "Pomodoro peek updates countdown only when it changes" "if next_face_value ~= face_value then")
require_pattern("${pomodoro}" "Pomodoro peek updates control text only when it changes" "if next_label ~= button_label then")
require_pattern("${pomodoro}" "Pomodoro peek updates control colour only when it changes" "if next_accent ~= button_accent then")
require_pattern("${pomodoro}" "Pomodoro peek timer has fixed layout bounds" "w = face_w, h = face_h")
require_pattern("${launcher}" "returning from an app restores live home tick" "painted.was_in_app = false")
forbid_pattern("${launcher}" "returning from an app must not trigger snapshot mid-transition" "if painted.was_in_app then")
forbid_pattern("${pager}" "pager end must not rebuild a full snapshot" "refresh_page_snapshot(settled_page)")

# A failed GT911 transaction must never reuse the driver's previous point. The
# tighter limit makes a short intentional horizontal drag enter paging before
# release, while a faster indev timer supplies enough samples for a quick flick.
require_pattern("${indev}" "touch read error handled" "esp_lcd_touch_read_data(tp) != ESP_OK")
require_pattern("${indev}" "short pager drag threshold" "lv_indev_set_scroll_limit(indev, 4)")
require_pattern("${indev}" "fast touch queue draining" "lv_timer_set_period(lv_indev_get_read_timer(indev), 4)")
require_pattern("${voice_ui}" "60hz script event dispatch" "#define VOICE_UI_TICK_MS       16")
require_pattern("${voice_ui}" "script task runs off the LVGL core" "#define VOICE_UI_TASK_CORE     0")
require_pattern("${voice_ui}" "script task cannot preempt the sampler" "#define VOICE_UI_TASK_PRIO     4")
require_pattern("${voice_ui}" "script task is pinned" "xTaskCreatePinnedToCore(voice_ui_task")

# Render and input read on the same LVGL task. A quick physical drag can begin
# and end while rendering is busy, so the driver must capture GT911 samples
# independently. The reader deliberately consumes one semantic sample per indev
# timer pass: draining a historical gesture with `continue_reading` makes the
# page jump through stale coordinates before the next rendered frame.
require_pattern("${indev}" "independent GT911 sampler task" "lua_lvgl_touch_sampler_task")
require_pattern("${touch_queue}" "preallocated buffered touch samples" "LUA_LVGL_TOUCH_SAMPLE_QUEUE_LEN")
require_pattern("${indev}" "buffered touch sample dequeue" "lua_lvgl_touch_sample_pop")
require_pattern("${indev}" "cross-core sample queue lock" "portENTER_CRITICAL")
require_pattern("${indev}" "LVGL paces buffered samples" "data->continue_reading = false")
forbid_pattern("${indev}" "LVGL must not replay a whole historical gesture" "data->continue_reading = has_more")
require_pattern("${indev}" "fixed cadence GT911 polling" "vTaskDelayUntil")
require_pattern("${indev}" "touch sampler wakes the LVGL task" "xTaskAbortDelay(task)")
forbid_pattern("${indev}" "touch indev must not double-read in event mode" "lv_indev_set_mode(indev, LV_INDEV_MODE_EVENT)")
require_pattern("${indev}" "sample bridge is lock-scoped" "lua_lvgl_indev_process_pending_locked")
require_pattern("${indev}" "sample bridge obtains the pointer timer" "lv_indev_get_read_timer(s_lvgl.touch_indev)")
require_pattern("${indev}" "sample bridge arms the pointer timer" "lv_timer_ready(read_timer);")
forbid_pattern("${indev}" "sample bridge must not manually read the indev" "lv_indev_read(s_lvgl.touch_indev)")
require_pattern("${runtime}" "sample bridge arms input before timer handling" "lua_lvgl_indev_process_pending_locked();")
require_pattern("${indev}" "pager trace drains after LVGL work" "lua_lvgl_indev_trace_drain_locked")
require_pattern("${indev}" "pager trace reports only per gesture" "[pager-trace]")
require_pattern("${indev}" "pager trace separates render time" "scroll->flush")
require_pattern("${indev}" "pager trace separates scanout time" "flush->present")
require_pattern("${indev}" "pager trace stores bounded same-frame samples" "LUA_LVGL_PAGER_TRACE_SLOW_FRAME_COUNT")
require_pattern("${indev}" "pager trace records a completed same-frame sample" "lua_lvgl_pager_trace_record_frame")
require_pattern("${indev}" "pager trace emits slow frames after a gesture" "[pager-frame]")
require_pattern("${indev}" "pager trace formats its gesture sequence numerically" "[pager-frame] #%")
require_pattern("${indev}" "pager trace formats its frame number numerically" "frame=%\"")
require_pattern("${indev}" "pager trace formats its total duration numerically" "total=%\"")
require_pattern("${indev}" "pager trace sample carries layout timing" "layout_ms")
require_pattern("${indev}" "pager trace sample carries render timing" "render_ms")
require_pattern("${indev}" "pager trace sample carries flush timing" "flush_ms")
require_pattern("${private}" "pager trace declares lifecycle stages" "LUA_LVGL_PAGER_TRACE_PHASE_RESTORE")
require_pattern("${private}" "pager trace accepts native lifecycle stage" "lua_lvgl_indev_trace_pager_phase_locked")
require_pattern("${indev}" "pager trace stores the stage with each refresh sample" ".phase = trace->frame_phase")
require_pattern("${indev}" "pager trace captures the stage at refresh start" "trace->frame_phase = sampler->pager_trace_phase")
require_pattern("${indev}" "pager trace writes a stage label after the gesture" "phase=%s")
require_pattern("${layout}" "native pager trace marks direct drag frames" "lua_lvgl_indev_trace_pager_phase_locked(LUA_LVGL_PAGER_TRACE_PHASE_DRAG)")
require_pattern("${layout}" "native pager trace marks release snap frames" "lua_lvgl_indev_trace_pager_phase_locked(LUA_LVGL_PAGER_TRACE_PHASE_SNAP)")
require_pattern("${layout}" "native pager trace marks live-layer restore frames" "lua_lvgl_indev_trace_pager_phase_locked(LUA_LVGL_PAGER_TRACE_PHASE_RESTORE)")
require_pattern("${indev}" "pager trace reads active-screen layout dirtiness" "lv_display_get_screen_active")
require_pattern("${indev}" "pager trace reads LVGL layout dirty bit" "scr_layout_inv")
require_pattern("${indev}" "pager trace captures display-root dirty mask" "frame_layout_dirty_mask")
require_pattern("${indev}" "pager trace retains bounded layout-step timing" "frame_layout_step_ms")
require_pattern("${indev}" "pager trace logs display-root dirty mask after a gesture" "layout-dirty=0x%02x")
require_pattern("${indev}" "pager trace logs bounded layout steps after a gesture" "layout-steps=")
require_pattern("${indev}" "pager trace counts dirty nodes by display root" "frame_layout_dirty_node_count")
require_pattern("${indev}" "pager trace counts dirty nodes in active-screen branches" "frame_active_branch_dirty_node_count")
require_pattern("${indev}" "pager trace captures aggregate dirty-node counts" "lua_lvgl_pager_trace_count_dirty_nodes")
require_pattern("${indev}" "pager trace logs active-screen branch aggregates" "active-branches=")
require_pattern("${indev}" "pager trace counts dirty nodes in pager children" "frame_pager_branch_dirty_node_count")
require_pattern("${indev}" "pager trace logs pager child aggregates" "pager-branches=")
forbid_pattern("${indev}" "pager trace must not log refresh events in the hot path" "[pager-frame] refresh")
require_pattern("${indev}" "unrecognised pager motion produces one trace" "result=no-scroll")
require_pattern("${indev}" "no-scroll trace waits for a delivered release" "!sampler->lvgl_gesture_active")
require_pattern("${indev}" "unfinished pager scroll produces one trace" "result=unfinished-scroll")
require_pattern("${indev}" "unfinished pager trace uses a bounded timeout" "LUA_LVGL_PAGER_TRACE_UNFINISHED_TIMEOUT_MS")
require_pattern("${indev}" "unfinished pager trace waits for a delivered release" "sampler->pager_trace.release_sample_ms != 0")
require_pattern("${runtime}" "flush submit is traced" "lua_lvgl_indev_trace_pager_flush_submitted")
require_pattern("${runtime}" "presentation completion is traced" "pager_trace_present_sequence++")
require_pattern("${runtime}" "pager trace drains after frame processing" "lua_lvgl_indev_trace_drain_locked();")
require_pattern("${touch_queue}" "completed gesture discard API" "lua_lvgl_touch_sample_queue_discard_completed")
require_pattern("${indev}" "new press supersedes unread completed gesture" "sample.kind == LUA_LVGL_TOUCH_SAMPLE_PRESS")
require_pattern("${indev}" "unread gesture can be replaced outright" "if (!sampler->lvgl_gesture_active)")
require_pattern("${touch_queue}" "active gesture release boundary API" "lua_lvgl_touch_sample_queue_retain_release_boundary")
require_pattern("${indev}" "new press terminates delivered gesture before replacement" "lua_lvgl_touch_sample_queue_retain_release_boundary")
require_pattern("${indev}" "transient I2C error grace" "LUA_LVGL_TOUCH_ERROR_GRACE_SAMPLES")
require_pattern("${indev}" "transient no-contact grace" "LUA_LVGL_TOUCH_NO_CONTACT_GRACE_SAMPLES 3")

# MIPI production uses esp_lvgl_adapter's worker rather than lua_lvgl_task.
# The sampler must therefore bridge pending samples through a small LVGL timer
# owned by that worker; otherwise the hand-rolled task's input wake path and
# pager trace never run on the shipped display route.
require_pattern("${private}" "adapter touch bridge state" "touch_bridge_timer")
require_pattern("${indev}" "adapter touch bridge callback" "lua_lvgl_indev_adapter_bridge_timer_cb")
require_pattern("${indev}" "adapter touch bridge created" "lv_timer_create(lua_lvgl_indev_adapter_bridge_timer_cb")
require_pattern("${indev}" "adapter touch bridge arms native input timer" "lua_lvgl_indev_process_pending_locked();")
require_pattern("${indev}" "adapter touch bridge drains pager trace" "lua_lvgl_indev_trace_drain_locked();")
require_pattern("${indev}" "adapter touch bridge teardown" "lv_timer_delete(s_lvgl.touch_bridge_timer)")
require_pattern("${indev}" "adapter touch bridge is adapter scoped" "if (s_lvgl.adapter_active)")

# The adapter owns the production handler, so the native DPI completion probe
# cannot see its partial-strip presents. Measure the LVGL phases directly with
# display events instead: the callback is timestamp-only and runs in the same
# adapter worker that owns the refresh.
require_pattern("${private}" "display event trace hook declaration" "lua_lvgl_indev_trace_display_event_locked")
require_pattern("${runtime}" "display event trace callback" "lua_lvgl_pager_trace_display_event_cb")
require_pattern("${runtime}" "display event trace registered" "lv_display_add_event_cb(display, lua_lvgl_pager_trace_display_event_cb, LV_EVENT_ALL, NULL);")
require_pattern("${runtime}" "display trace forwards layout completion" "case LV_EVENT_UPDATE_LAYOUT_COMPLETED:")
require_pattern("${indev}" "trace records refresh work" "LV_EVENT_REFR_START")
require_pattern("${indev}" "trace records render work" "LV_EVENT_RENDER_START")
require_pattern("${indev}" "trace records refresh-frame pacing" "max-frame-gap")
require_pattern("${indev}" "trace retains the prior refresh boundary" "last_refresh_started_ms")
require_pattern("${indev}" "trace records first-motion response" "move->scroll")
require_pattern("${indev}" "trace records flush call work" "LV_EVENT_FLUSH_START")
require_pattern("${indev}" "trace records flush wait work" "LV_EVENT_FLUSH_WAIT_START")
require_pattern("${indev}" "trace reports longest refresh" "max-refresh")
require_pattern("${indev}" "trace records layout completion" "LV_EVENT_UPDATE_LAYOUT_COMPLETED")
require_pattern("${indev}" "trace reports longest layout" "max-layout")
require_pattern("${indev}" "trace reports post-layout refresh preparation" "max-post-layout")
require_pattern("${indev}" "trace reports longest render" "max-render")
require_pattern("${indev}" "trace reports longest flush" "max-flush")
require_pattern("${indev}" "trace reports longest flush wait" "max-wait")

# A snapshot drag invalidates almost the full pager viewport on every frame.
# With three existing RGB565 panel buffers, the adapter's TRIPLE_FULL route is
# the documented large-area mode: LVGL renders directly into a non-visible
# full frame rather than splitting each bitmap move into partial draw stripes.
require_pattern("${display_bringup}" "triple full has three panel framebuffers" "dpi_cfg.num_fbs = 3")
require_pattern("${runtime}" "adapter triple full selected" "ESP_LV_ADAPTER_TEAR_AVOID_MODE_TRIPLE_FULL")
require_pattern("${runtime}" "adapter display registered" "esp_lv_adapter_register_display")
forbid_pattern("${voice_ui}" "launcher must not force direct two-buffer rendering" "render=\\\"direct\\\"")

# A DPI framebuffer switch is asynchronous: waiting on VSYNC inside the LVGL
# task makes every presented frame also an input-processing stall. The panel
# refresh callback is the safe ownership boundary for lv_display_flush_ready.
require_pattern("${runtime}" "direct flush completion is asynchronous" "Direct FB swaps are asynchronous")
require_pattern("${runtime}" "refresh callback releases direct framebuffer" "lv_display_flush_ready(display);")
require_pattern("${runtime}" "idle DPI scans leave LVGL flush state untouched" "state && state->flush_pending")
forbid_pattern("${runtime}" "direct flush must not block on VSYNC" "fb-swap flush wait timeout")

# ESP32-P4's MIPI pager repeatedly moves PSRAM-backed RGB565 frame data. Keep
# the durable defaults aligned with Espressif's P4 cache/XIP recommendations
# and ensure this is a performance, rather than debug, firmware build.
require_pattern("${sdkconfig_defaults}" "P4 pager compiler profile" "CONFIG_COMPILER_OPTIMIZATION_PERF=y")
require_pattern("${sdkconfig_defaults}" "P4 pager PSRAM XIP" "CONFIG_SPIRAM_XIP_FROM_PSRAM=y")
require_pattern("${sdkconfig_defaults}" "P4 pager L2 capacity" "CONFIG_CACHE_L2_CACHE_256KB=y")
require_pattern("${sdkconfig_defaults}" "P4 pager L2 line width" "CONFIG_CACHE_L2_CACHE_LINE_128B=y")
require_pattern("${sdkconfig_defaults}" "P4 pager draw-buffer alignment" "CONFIG_LV_DRAW_BUF_ALIGN=128")
require_pattern("${sdkconfig_defaults}" "P4 pager PPA image compositor" "CONFIG_LV_USE_PPA_IMG=y")
require_pattern("${board_sdkconfig_defaults}" "P4 board draw-buffer alignment" "CONFIG_LV_DRAW_BUF_ALIGN=128")

# The LVGL task must use an absolute cadence. A relative vTaskDelay adds a
# second 2 ms wait after any long draw/flush pass, directly increasing the
# time before the next GT911 sample can reach the pager.
require_pattern("${runtime}" "LVGL task uses a fixed wake cadence" "vTaskDelayUntil(&next_wake")
forbid_pattern("${runtime}" "LVGL task must not add a post-render delay" "vTaskDelay(pdMS_TO_TICKS(state->task_period_ms")
