#!/usr/bin/env python3
"""Keep the adapter's LVGL-v9 PPA path safe for 128-byte P4 cache lines.

The esp_lvgl_adapter custom blend handler asks the PPA driver to render into
LVGL layers.  PPA validates every output buffer against the *PSRAM DMA* cache
alignment, even if the current layer happens to be internal RAM.  The upstream
handler only checked the cache-line size of the layer address and used
``ESP_ERROR_CHECK`` for an invalid operation.  On a P4 configured with a
128-byte external cache line, a valid LVGL snapshot layer could therefore
abort the UI task during snapshot pre-rendering.

This patch makes the handler use the same requirement as ``ppa_core.c`` and
falls back to LVGL's software blend routine whenever the hardware path is not
eligible.  It also reports the real RGB565 output size (two bytes per pixel),
instead of ``sizeof(lv_color_t)`` which is three bytes in LVGL 9.

``managed_components/`` is regenerated by the component manager, so this
script runs during CMake configuration and is deliberately idempotent.
"""
from __future__ import annotations

import pathlib
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
TARGET = (
    ROOT
    / "managed_components"
    / "espressif__esp_lvgl_adapter"
    / "src"
    / "display"
    / "bridge"
    / "v9"
    / "lvgl_ppa_accel_v9.c"
)
MARKER = "CERB_PPA_ALIGNMENT_HARDENED"


def replace_required(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise ValueError(f"missing {label}")
    return text.replace(old, new, 1)


def main() -> int:
    if not TARGET.is_file():
        print(f"[patch_adapter_ppa] skip missing {TARGET.relative_to(ROOT)}")
        return 0

    text = TARGET.read_text(encoding="utf-8")
    if MARKER in text:
        print("[patch_adapter_ppa] already applied")
        return 0

    try:
        text = replace_required(
            text,
            '#include "esp_cache.h"\n',
            '#include "esp_cache.h"\n'
            '#include "esp_private/esp_cache_private.h"\n'
            '#include "esp_heap_caps.h"\n',
            "cache alignment includes",
        )
        text = replace_required(
            text,
            "static void ppa_blend(lv_color_t *bg_buf, const lv_area_t *bg_area, const lv_color_t *fg_buf,\n"
            "                      const lv_area_t *fg_area, uint16_t fg_stride_px, const lv_area_t *block_area, lv_opa_t opa);\n"
            "static void ppa_fill(lv_color_t *bg_buf, const lv_area_t *bg_area, const lv_area_t *block_area, lv_color_t color);\n",
            "static esp_err_t ppa_blend(lv_color_t *bg_buf, const lv_area_t *bg_area, const lv_color_t *fg_buf,\n"
            "                           const lv_area_t *fg_area, uint16_t fg_stride_px, const lv_area_t *block_area, lv_opa_t opa);\n"
            "static esp_err_t ppa_fill(lv_color_t *bg_buf, const lv_area_t *bg_area, const lv_area_t *block_area, lv_color_t color);\n",
            "PPA operation prototypes",
        )
        text = replace_required(
            text,
            "static size_t ppa_get_cache_line_size(const void *addr);\n"
            "static size_t ppa_get_aligned_buffer_size(const void *addr, size_t size);\n"
            "static bool ppa_buffer_cache_aligned(const void *addr);\n",
            "static size_t ppa_get_cache_line_size(const void *addr);\n"
            "static size_t ppa_get_hardware_alignment(void);\n"
            "static size_t ppa_get_aligned_buffer_size(const void *addr, size_t size);\n"
            "static bool ppa_buffer_cache_aligned(const void *addr);\n",
            "PPA alignment prototype",
        )
        text = replace_required(
            text,
            "static size_t ppa_get_cache_line_size(const void *addr)\n"
            "{\n"
            "    if (!addr) {\n"
            "        return 0;\n"
            "    }\n"
            "\n"
            "    return display_bridge_get_cache_line_size_by_addr(addr);\n"
            "}\n"
            "\n"
            "static size_t ppa_get_aligned_buffer_size(const void *addr, size_t size)\n"
            "{\n"
            "    size_t align = ppa_get_cache_line_size(addr);\n"
            "\n"
            "    return (align > 0) ? LVGL_PORT_PPA_ALIGN_UP(size, align) : size;\n"
            "}\n"
            "\n"
            "static bool ppa_buffer_cache_aligned(const void *addr)\n"
            "{\n"
            "    size_t align = ppa_get_cache_line_size(addr);\n"
            "\n"
            "    return (align == 0) || (((uintptr_t)addr & (align - 1)) == 0);\n"
            "}\n",
            "static size_t ppa_get_cache_line_size(const void *addr)\n"
            "{\n"
            "    if (!addr) {\n"
            "        return 0;\n"
            "    }\n"
            "\n"
            "    return display_bridge_get_cache_line_size_by_addr(addr);\n"
            "}\n"
            "\n"
            "static size_t ppa_get_hardware_alignment(void)\n"
            "{\n"
            "    size_t alignment = 0;\n"
            "    if (esp_cache_get_alignment(MALLOC_CAP_SPIRAM | MALLOC_CAP_DMA, &alignment) != ESP_OK ||\n"
            "            alignment == 0) {\n"
            "        alignment = LVGL_PORT_PPA_ALIGNMENT;\n"
            "    }\n"
            "    return alignment;\n"
            "}\n"
            "\n"
            "static size_t ppa_get_aligned_buffer_size(const void *addr, size_t size)\n"
            "{\n"
            "    (void)addr;\n"
            "    return LVGL_PORT_PPA_ALIGN_UP(size, ppa_get_hardware_alignment());\n"
            "}\n"
            "\n"
            "/* " + MARKER + ": match ppa_core's output-buffer requirement. */\n"
            "static bool ppa_buffer_cache_aligned(const void *addr)\n"
            "{\n"
            "    const size_t align = ppa_get_hardware_alignment();\n"
            "    return align == 0 || (((uintptr_t)addr & (align - 1)) == 0);\n"
            "}\n",
            "PPA alignment implementation",
        )
        text = replace_required(
            text,
            "static void ppa_blend(lv_color_t *bg_buf, const lv_area_t *bg_area, const lv_color_t *fg_buf,\n"
            "                      const lv_area_t *fg_area, uint16_t fg_stride_px, const lv_area_t *block_area, lv_opa_t opa)\n",
            "static esp_err_t ppa_blend(lv_color_t *bg_buf, const lv_area_t *bg_area, const lv_color_t *fg_buf,\n"
            "                           const lv_area_t *fg_area, uint16_t fg_stride_px, const lv_area_t *block_area, lv_opa_t opa)\n",
            "RGB565 blend return type",
        )
        text = replace_required(
            text,
            "static void ppa_fill(lv_color_t *bg_buf, const lv_area_t *bg_area, const lv_area_t *block_area, lv_color_t color)\n",
            "static esp_err_t ppa_fill(lv_color_t *bg_buf, const lv_area_t *bg_area, const lv_area_t *block_area, lv_color_t color)\n",
            "RGB565 fill return type",
        )
        text = text.replace(
            "ppa_get_aligned_buffer_size(bg_buf, sizeof(lv_color_t) * bg_w * bg_h)",
            "ppa_get_aligned_buffer_size(bg_buf, (size_t)bg_w * bg_h * 2U)",
            2,
        )
        text = replace_required(
            text,
            "    ESP_ERROR_CHECK(ppa_do_blend(s_blend_handle, &cfg));\n",
            "    return ppa_do_blend(s_blend_handle, &cfg);\n",
            "RGB565 PPA blend abort",
        )
        text = replace_required(
            text,
            "    ESP_ERROR_CHECK(ppa_do_fill(s_fill_handle, &cfg));\n",
            "    return ppa_do_fill(s_fill_handle, &cfg);\n",
            "RGB565 PPA fill abort",
        )
        text = replace_required(
            text,
            "        ppa_blend(bg_buf, &layer->buf_area, (const lv_color_t *)dsc->src_buf,\n"
            "                  src_area, src_stride_px, &block_area, dsc->opa);\n"
            "\n"
            "        /* Invalidate cache after PPA writes */\n"
            "        ppa_cache_invalidate(&block_area, &layer->buf_area, bg_buf, 2);\n"
            "        return;\n",
            "        if (ppa_blend(bg_buf, &layer->buf_area, (const lv_color_t *)dsc->src_buf,\n"
            "                      src_area, src_stride_px, &block_area, dsc->opa) == ESP_OK) {\n"
            "            /* Invalidate cache after PPA writes */\n"
            "            ppa_cache_invalidate(&block_area, &layer->buf_area, bg_buf, 2);\n"
            "            return;\n"
            "        }\n"
            "        lv_draw_ppa_v9_sw_fallback(t, dsc);\n"
            "        return;\n",
            "RGB565 blend fallback",
        )
        text = replace_required(
            text,
            "    if (dsc->opa >= LV_OPA_MAX) {\n"
            "        ppa_fill(bg_buf, &layer->buf_area, &block_area, dsc->color);\n"
            "        ppa_cache_invalidate(&block_area, &layer->buf_area, bg_buf, 2);\n"
            "        return;\n"
            "    }\n",
            "    if (dsc->opa >= LV_OPA_MAX) {\n"
            "        if (ppa_fill(bg_buf, &layer->buf_area, &block_area, dsc->color) == ESP_OK) {\n"
            "            ppa_cache_invalidate(&block_area, &layer->buf_area, bg_buf, 2);\n"
            "            return;\n"
            "        }\n"
            "        lv_draw_ppa_v9_sw_fallback(t, dsc);\n"
            "        return;\n"
            "    }\n",
            "RGB565 fill fallback",
        )
        text = replace_required(
            text,
            "static void ppa_fill_rgb888(uint8_t *bg_buf, const lv_area_t *bg_area,\n"
            "                            const lv_area_t *block_area, lv_color_t color)\n",
            "static esp_err_t ppa_fill_rgb888(uint8_t *bg_buf, const lv_area_t *bg_area,\n"
            "                                 const lv_area_t *block_area, lv_color_t color)\n",
            "RGB888 fill return type",
        )
        text = replace_required(
            text,
            "    ESP_ERROR_CHECK(ppa_do_fill(s_fill_handle, &cfg));\n",
            "    return ppa_do_fill(s_fill_handle, &cfg);\n",
            "RGB888 PPA fill abort",
        )
        text = replace_required(
            text,
            "            ESP_ERROR_CHECK(ppa_do_blend(s_blend_handle, &cfg));\n"
            "            ppa_cache_sync_region(&block_area, &layer->buf_area, bg_buf, 3, ESP_CACHE_MSYNC_FLAG_DIR_M2C);\n"
            "            return;\n",
            "            if (ppa_do_blend(s_blend_handle, &cfg) == ESP_OK) {\n"
            "                ppa_cache_sync_region(&block_area, &layer->buf_area, bg_buf, 3, ESP_CACHE_MSYNC_FLAG_DIR_M2C);\n"
            "                return;\n"
            "            }\n"
            "            lv_draw_ppa_v9_sw_fallback_rgb888(t, dsc);\n"
            "            return;\n",
            "RGB888 blend fallback",
        )
        text = replace_required(
            text,
            "    if (dsc->opa >= LV_OPA_MAX) {\n"
            "        ppa_fill_rgb888(bg_buf, &layer->buf_area, &block_area, dsc->color);\n"
            "        ppa_cache_sync_region(&block_area, &layer->buf_area, bg_buf, 3, ESP_CACHE_MSYNC_FLAG_DIR_M2C);\n"
            "        return;\n"
            "    }\n",
            "    if (dsc->opa >= LV_OPA_MAX) {\n"
            "        if (ppa_fill_rgb888(bg_buf, &layer->buf_area, &block_area, dsc->color) == ESP_OK) {\n"
            "            ppa_cache_sync_region(&block_area, &layer->buf_area, bg_buf, 3, ESP_CACHE_MSYNC_FLAG_DIR_M2C);\n"
            "            return;\n"
            "        }\n"
            "        lv_draw_ppa_v9_sw_fallback_rgb888(t, dsc);\n"
            "        return;\n"
            "    }\n",
            "RGB888 fill fallback",
        )
    except ValueError as error:
        print(f"[patch_adapter_ppa] error: {error}")
        return 1

    TARGET.write_text(text, encoding="utf-8")
    print(f"[patch_adapter_ppa] patched {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
