#!/usr/bin/env python3
"""Ensure gen_bmgr_codes REQUIRES the local display/touch components.

gen_bmgr_codes/CMakeLists.txt is regenerated by `idf.py bmgr` on every board
config pass, and its generated `REQUIRES esp_board_manager` does not include
the local (non-managed) esp_lcd_st7701 / esp_lcd_touch / esp_lcd_touch_gt911
components that this board's setup_device.c #includes. Without them the
gen_bmgr_codes build fails on dev_display_lcd.h's concrete drivers.

Run from CMake configure (and manually after `idf.py bmgr`). Idempotent:
skips when the REQUIRES line already lists the components.

This is generated-file patching, not a source edit — gen_bmgr_codes is
gitignored and refreshed by bmgr, so the project's tools/patch_*.py pattern
(fixing managed/generated components after they regenerate) applies.
"""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CMAKE = ROOT / "components" / "gen_bmgr_codes" / "CMakeLists.txt"

OLD = "    REQUIRES esp_board_manager\n"
NEW = "    REQUIRES esp_board_manager esp_lcd_st7701 esp_lcd_touch esp_lcd_touch_gt911\n"


def main() -> int:
    if not CMAKE.is_file():
        print(f"[patch_gen_bmgr_requires] skip missing {CMAKE.relative_to(ROOT)}")
        return 1
    text = CMAKE.read_text(encoding="utf-8")
    if NEW in text:
        print("[patch_gen_bmgr_requires] already applied")
        return 0
    if OLD not in text:
        print(f"[patch_gen_bmgr_requires] warn: REQUIRES line not found in {CMAKE.name}")
        return 1
    CMAKE.write_text(text.replace(OLD, NEW, 1), encoding="utf-8")
    print(f"[patch_gen_bmgr_requires] applied to {CMAKE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
