const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const script = fs.readFileSync(path.join(__dirname, '..', 'scripts', 'cm5-acceptance.sh'), 'utf8')

test('CM5 acceptance reports release, migration, service, runtime, and hardware evidence in one JSON contract', () => {
  assert.match(script, /SOURCE_DIR=/)
  assert.match(script, /ACTIVE_RUNTIME_DIR="\$\(readlink -f "\$current"\)"/)
  assert.match(script, /DIR="\$ACTIVE_RUNTIME_DIR"/)
  assert.match(script, /"active-release"/)
  assert.match(script, /"rollback-release"/)
  assert.match(script, /"kiosk-release-launcher"/)
  assert.match(script, /open-deskos-shell\.service/)
  assert.match(script, /"runtime-update-state"/)
  assert.match(script, /"runtime-migrations"/)
  assert.match(script, /"open-deskos-remote-bridge\.service"/)
  assert.match(script, /"graphical-session-autostart"/)
  assert.match(script, /import-environment DISPLAY WAYLAND_DISPLAY XAUTHORITY/)
  assert.match(script, /service_evidence "open-deskos-shell\.service" "true" "runtime"/)
  assert.match(script, /"kiosk-process"/)
  assert.match(script, /node_modules\/\.pnpm\/electron/)
  assert.match(script, /"open-deskos-face-agent\.service"/)
  assert.doesNotMatch(script, /autostart-entry/)
  assert.match(script, /"smoke-run"/)
  assert.match(script, /"display-mode"/)
  assert.match(script, /"touch-devices"/)
  assert.match(script, /"required"/)
  assert.match(script, /"class"/)
  assert.match(script, /\[ "\$FAILURES" -eq 0 \]/)
})
