const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

const service = fs.readFileSync('../../experiments/vision/face-agent/systemd/open-deskos-face-agent.service', 'utf8')
const installer = fs.readFileSync('scripts/cm5-install.sh', 'utf8')

test('defines a restartable user service for the installed Face Agent', () => {
  assert.match(service, /^Description=Open DeskOS Face Agent$/m)
  assert.match(service, /^ExecStart=\/opt\/face-agent-venv\/bin\/python3 \/opt\/face-agent\/face_service\.py$/m)
  assert.match(service, /^Restart=always$/m)
  assert.match(service, /^RestartSec=3$/m)
})

test('provisions experimental local Face Agent dependencies only when opted in', () => {
  assert.match(installer, /FACE_AGENT_DIR="\/opt\/face-agent"/)
  assert.match(installer, /python3-venv python3-opencv python3-aiohttp python3-numpy/)
  assert.match(service, /Environment=FACE_AGENT_DEVICE=\/dev\/open-deskos-p4-camera/)
  assert.match(service, /Environment=FACE_AGENT_WIDTH=1280/)
  assert.match(service, /Environment=FACE_AGENT_HEIGHT=720/)
  assert.match(service, /Environment=FACE_AGENT_FPS=30/)
  assert.match(installer, /python3-venv python3-opencv python3-aiohttp python3-numpy python3-serial/)
  assert.match(installer, /python3 -m venv --system-site-packages "\$\{FACE_AGENT_VENV\}"/)
  assert.match(installer, /"\$\{FACE_AGENT_VENV\}\/bin\/pip" install --upgrade pyserial onnxruntime opencv-contrib-python-headless/)
  assert.match(installer, /99-open-deskos-p4-camera\.rules/)
  assert.match(installer, /SYMLINK\+="open-deskos-p4-camera"/)
  assert.match(installer, /FACE_AGENT_SOURCE="\$\{REPOSITORY_ROOT\}\/experiments\/vision\/face-agent"/)
  assert.match(installer, /install -o root -g root -m 0644 "\$\{FACE_AGENT_SOURCE\}\/face_service\.py"/)
  assert.match(installer, /open-deskos-face-agent\.service/)
  assert.match(installer, /ODESK_INSTALL_EXPERIMENTAL_VISION:-0/)
  assert.match(installer, /if \[ "\$\{ODESK_INSTALL_EXPERIMENTAL_VISION:-0\}" = "1" \]; then/)
  assert.match(installer, /skipping experimental Face Agent and ESP32-P4 camera provisioning/)
  assert.match(installer, /BRIDGE_UNIT_DIR="\$\{TARGET_HOME\}\/.config\/systemd\/user"/)
  assert.match(installer, /run_as_target_user systemctl --user enable --now open-deskos-remote-bridge\.service/)
  assert.match(installer, /OPENBOX_CONFIG_DIR="\$\{TARGET_HOME\}\/.config\/openbox"/)
  assert.match(installer, /run_as_target_user mkdir -p "\$OPENBOX_CONFIG_DIR"/)
  assert.match(installer, /chown -R "\$\{TARGET_UID\}:\$\{TARGET_GID\}" "\$OPENBOX_CONFIG_DIR"/)
  assert.match(installer, /run_as_target_user sed -i 's\/<name>\.\*<\\\/name>\/<name>OpenDeskOS<\\\/name>\/' "\$OPENBOX_CONFIG_DIR\/rc\.xml"/)
  assert.match(installer, /AUTOSTART_DIR="\$\{TARGET_HOME\}\/.config\/autostart"/)
  assert.match(installer, /chown "\$\{TARGET_UID\}:\$\{TARGET_GID\}" "\$AUTOSTART_DIR\/open-deskos-shell\.desktop"/)

  const experimentalInstall = installer.indexOf('install_experimental_vision')
  const kioskAutostart = installer.indexOf('== registering kiosk autostart ==')
  assert.ok(experimentalInstall >= 0)
  assert.ok(experimentalInstall < kioskAutostart)
})
