const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

const service = fs.readFileSync('../../experiments/vision/face-agent/systemd/open-deskos-face-agent.service', 'utf8')
const installer = fs.readFileSync('scripts/cm5-install.sh', 'utf8')

test('defines a restartable user service for the installed Face Agent', () => {
  assert.match(service, /^Description=Open DeskOS Face Agent$/m)
  assert.match(service, /^ExecStart=\/opt\/face-agent-venv\/bin\/python3 \/opt\/face-agent\/face_service\.py$/m)
  assert.match(service, /^Restart=always$/m)
  assert.match(service, /^RestartSec=3$/m)
})

test('provisions experimental ESP32-P4 Face Agent dependencies only when opted in', () => {
  assert.match(installer, /FACE_AGENT_DIR="\/opt\/face-agent"/)
  assert.match(service, /Environment=FACE_AGENT_DEVICE=\/dev\/open-deskos-p4-camera/)
  assert.match(installer, /python3-venv python3-aiohttp python3-serial/)
  assert.match(installer, /python3 -m venv --system-site-packages "\$\{FACE_AGENT_VENV\}"/)
  assert.match(installer, /"\$\{FACE_AGENT_VENV\}\/bin\/pip" install --upgrade pyserial/)
  assert.doesNotMatch(installer, /opencv|onnxruntime|python3-numpy/)
  assert.match(installer, /99-open-deskos-p4-camera\.rules/)
  assert.match(installer, /SYMLINK\+="open-deskos-p4-camera"/)
  assert.match(installer, /FACE_AGENT_SOURCE="\$\{REPOSITORY_ROOT\}\/experiments\/vision\/face-agent"/)
  assert.match(installer, /install -o root -g root -m 0644 "\$\{FACE_AGENT_SOURCE\}\/face_service\.py"/)
  assert.match(installer, /ODESK_INSTALL_EXPERIMENTAL_VISION:-0/)
  assert.match(installer, /skipping experimental Face Agent and ESP32-P4 camera provisioning/)
  assert.match(installer, /BRIDGE_UNIT_DIR="\$\{TARGET_HOME\}\/\.config\/systemd\/user"/)
  assert.match(installer, /run_as_target_user systemctl --user enable --now open-deskos-remote-bridge\.service/)

  const experimentalInstall = installer.indexOf('install_experimental_vision')
  const initialRelease = installer.indexOf('== establishing the initial immutable Open DeskOS release ==')
  assert.ok(experimentalInstall >= 0)
  assert.ok(experimentalInstall < initialRelease)
})

test('establishes an initial immutable release and a restartable kiosk service', () => {
  assert.match(installer, /RELEASES_DIR="\$\{RUNTIME_ROOT\}\/releases"/)
  assert.match(installer, /install -d -o "\$\{TARGET_UID\}" -g "\$\{TARGET_GID\}" -m 0755 "\$\{RELEASE_DIR\}"/)
  assert.match(installer, /run_as_target_user cp -a "\$\{DIR\}\/\." "\$\{RELEASE_DIR\}\//)
  assert.doesNotMatch(installer, /if \[ -d "\$\{RUNTIME_ROOT\}\/current" \]; then\n  \$SUDO chown/)
  assert.match(installer, /\$SUDO chown -R root:root "\$\{RELEASE_DIR\}"/)
  assert.match(installer, /\$SUDO chmod -R a-w "\$\{RELEASE_DIR\}"/)
  assert.match(installer, /release\.json/)
  assert.match(installer, /ln -sfn "\$\{RELEASE_DIR\}" "\$\{RUNTIME_ROOT\}\/current"/)
  assert.match(installer, /ODK_CANDIDATE_RELEASE="\$\{RELEASE_DIR\}"/)
  assert.match(installer, /scripts\/update-runtime\.js/)
  const kioskUnit = installer.indexOf('KIOSK_UNIT_DIR=')
  const updateTransaction = installer.indexOf('scripts/update-runtime.js')
  assert.ok(kioskUnit >= 0)
  assert.ok(kioskUnit < updateTransaction)
  assert.match(installer, /scripts\/validate-release\.js/)
  assert.match(installer, /KIOSK_UNIT_DIR="\$\{TARGET_HOME\}\/\.config\/systemd\/user"/)
  assert.match(installer, /ExecStart=\$\{RUNTIME_ROOT\}\/current\/scripts\/start-kiosk\.sh/)
  assert.match(installer, /After=graphical-session\.target/)
  assert.match(installer, /PartOf=graphical-session\.target/)
  assert.match(installer, /AUTOSTART_DIR="\$\{TARGET_HOME\}\/\.config\/autostart"/)
  assert.match(installer, /loginctl show-session/)
  assert.match(installer, /GRAPHICAL_DISPLAY/)
  assert.match(installer, /systemctl --user import-environment DISPLAY/)
  assert.match(installer, /systemctl --user restart open-deskos-shell\.service/)
})

test('keeps kiosk user dependency installation and generated assets writable', () => {
  assert.match(installer, /HOME="\$\{TARGET_HOME\}"/)
  assert.match(installer, /USER="\$\{TARGET_USER\}"/)
  assert.match(installer, /TARGET_NODE="\$\(runuser -u "\$\{TARGET_USER\}"/)
  assert.match(installer, /NODE_BIN="\$\(dirname "\$\(readlink -f "\$\{TARGET_NODE\}"\)"\)"/)
  assert.match(installer, /COREPACK_PNPM="\$\{NODE_BIN\}\/corepack"/)
  assert.match(installer, /PATH="\$\{KIOSK_BIN:-\$\{NODE_BIN:-\/usr\/local\/bin\}\}:\$\{NODE_BIN:-\/usr\/local\/bin\}:\/usr\/local\/bin:\/usr\/bin:\/bin"/)
  assert.match(installer, /COREPACK_ENABLE_PROJECT_SPEC=0/)
  assert.match(installer, /KIOSK_BIN="\$\{TARGET_HOME\}\/\.local\/lib\/open-deskos\/bin"/)
  assert.match(installer, /\$\{KIOSK_BIN\}\/pnpm/)
  assert.match(installer, /run_as_target_user pnpm install --frozen-lockfile/)
  assert.match(installer, /\$SUDO chown -R "\$\{TARGET_UID\}:\$\{TARGET_GID\}" "\$\{DIR\}"/)
  assert.match(installer, /run_as_target_user npm install/)
  assert.match(installer, /apt-get update \|\| echo "apt-get update failed; using cached package indexes"/)
  assert.match(installer, /run_as_target_user "\$\{DIR\}\/node_modules\/\.bin\/unocss"/)
})
