const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const REPOSITORY_ROOT = require('./helpers/repo-root').findRepositoryRoot(__dirname)
const CAMERA_ROOT = path.join(REPOSITORY_ROOT, 'peripherals', 'esp32-p4-camera')
const FEATURE_PATH = path.join(CAMERA_ROOT, 'tests', 'features', 'p4-camera.feature')
const README_PATH = path.join(CAMERA_ROOT, 'README.md')
const C_SOURCE_PATH = path.join(CAMERA_ROOT, 'main', 'p4_camera_protocol.c')
const C_HEADER_PATH = path.join(CAMERA_ROOT, 'main', 'p4_camera_protocol.h')
const CAMERA_MAIN_PATH = path.join(CAMERA_ROOT, 'main', 'p4_camera_main.c')
const INFERENCE_PATH = path.join(CAMERA_ROOT, 'main', 'p4_face_inference.cpp')
const INSTALL_PATH = path.join(__dirname, '..', 'scripts', 'cm5-install.sh')
const SDKCONFIG_DEFAULTS_PATH = path.join(CAMERA_ROOT, 'sdkconfig.defaults')
const KCONFIG_PATH = path.join(CAMERA_ROOT, 'main', 'Kconfig.projbuild')
const COMPONENT_MANIFEST_PATH = path.join(CAMERA_ROOT, 'main', 'idf_component.yml')
const CMAKE_PATH = path.join(CAMERA_ROOT, 'main', 'CMakeLists.txt')
const AUDIO_HEADER_PATH = path.join(CAMERA_ROOT, 'main', 'p4_usb_microphone.h')
const AUDIO_SOURCE_PATH = path.join(CAMERA_ROOT, 'main', 'p4_usb_microphone.c')
const USB_DESCRIPTORS_PATH = path.join(CAMERA_ROOT, 'main', 'usb_descriptors.c')
const HARDWARE_ACCEPTANCE_PATH = path.join(__dirname, '..', 'scripts', 'p4-microphone-acceptance.sh')

test('P4 camera sub-device BDD feature defines MIPI CSI SC2336 contract', () => {
  assert.ok(fs.existsSync(FEATURE_PATH), 'p4-camera.feature must exist')
  const feature = fs.readFileSync(FEATURE_PATH, 'utf8')
  assert.match(feature, /Feature: ESP32-P4 SC2336 camera subsystem/)
  assert.match(feature, /SC2336 1080P CMOS image sensor/)
  assert.match(feature, /SDA GPIO 7 and SCL GPIO 8/)
  assert.match(feature, /GPIO 26/)
  assert.match(feature, /MIPI CSI-2/)
  assert.match(feature, /Real on-device face detection and recognition metadata/)
  assert.match(feature, /rather than emitting a fixed face count/)
  assert.match(feature, /Physical owner enrollment and recognition/)
  assert.match(feature, /owner-confirmation button is physically pressed/)
  assert.match(feature, /Enrollment fails closed without valid physical confirmation/)
  assert.match(feature, /experimental owner-recognition result remains unavailable/)
  assert.match(feature, /exactly one valid face is visible to the P4 camera/)
  assert.match(feature, /confirmation request that outlives its 30 second window is also cleared/)
  assert.match(feature, /Temporary local diagnostic snapshot for hardware alignment/)
  assert.match(feature, /production image does not expose a camera preview or diagnostic snapshot/)
  assert.match(feature, /Structured face recognition metadata protocol/)
})

test('P4 camera sub-device README defines pinout and build commands', () => {
  assert.ok(fs.existsSync(README_PATH), 'README.md must exist')
  const readme = fs.readFileSync(README_PATH, 'utf8')
  assert.match(readme, /SC2336/)
  assert.match(readme, /ESP32-P4/)
  assert.match(readme, /GPIO 7/)
  assert.match(readme, /GPIO 8/)
  assert.match(readme, /GPIO 26/)
  assert.match(readme, /idf\.py set-target esp32p4/)
})

test('P4 camera physical enrollment accepts only an immediate single-face BOOT confirmation', () => {
  const main = fs.readFileSync(CAMERA_MAIN_PATH, 'utf8')
  const inference = fs.readFileSync(INFERENCE_PATH, 'utf8')
  assert.match(main, /CONFIG_APP_CAMERA_OWNER_CONFIRM_PIN/)
  assert.match(main, /GPIO_INTR_NEGEDGE/)
  assert.match(main, /s_owner_enrollment_pending = true/)
  assert.match(main, /if \(!s_owner_enrollment_pending \|\| !owner_confirmation_active\(\)\)/)
  assert.match(main, /metadata->faces_count != 1 \|\| metadata->current_face_index != 0/)
  assert.match(main, /Owner enrollment cancelled: exactly one face was not visible at confirmation/)
  assert.doesNotMatch(main, /ENROLL /)
  assert.doesNotMatch(main, /command_reader/)
  assert.match(inference, /enrollment_input\.size\(\) != 1/)
  assert.match(inference, /RECOGNITION_THRESHOLD = 0\.75F/)
})

test('P4 diagnostic snapshots require an explicitly enabled diagnostic build', () => {
  const main = fs.readFileSync(CAMERA_MAIN_PATH, 'utf8')
  const kconfig = fs.readFileSync(KCONFIG_PATH, 'utf8')
  const sdkconfig = fs.readFileSync(SDKCONFIG_DEFAULTS_PATH, 'utf8')
  assert.match(kconfig, /config APP_CAMERA_DIAGNOSTIC_SNAPSHOT/)
  assert.match(kconfig, /default n/)
  assert.match(main, /#if CONFIG_APP_CAMERA_DIAGNOSTIC_SNAPSHOT/)
  assert.match(main, /P4_SNAPSHOT_BEGIN/)
  assert.match(main, /P4_SNAPSHOT_DATA/)
  assert.match(main, /DIAGNOSTIC_SNAPSHOT_LINE_BYTES 16/)
  assert.match(main, /CONFIG_APP_CAMERA_DIAGNOSTIC_SNAPSHOT_DELAY_SECONDS/)
  assert.match(main, /#if !CONFIG_APP_CAMERA_DIAGNOSTIC_SNAPSHOT/)
  assert.match(kconfig, /config APP_CAMERA_DIAGNOSTIC_SNAPSHOT_DELAY_SECONDS/)
  assert.doesNotMatch(sdkconfig, /CONFIG_APP_CAMERA_DIAGNOSTIC_SNAPSHOT=y/)
})

test('P4 native composite USB identity matches the CM5 stable metadata rule', () => {
  const installer = fs.readFileSync(INSTALL_PATH, 'utf8')
  const sdkconfig = fs.readFileSync(SDKCONFIG_DEFAULTS_PATH, 'utf8')
  const descriptors = fs.readFileSync(USB_DESCRIPTORS_PATH, 'utf8')
  assert.match(descriptors, /#define USB_VID 0x303A/)
  assert.match(descriptors, /#define USB_PID 0x7002/)
  assert.match(installer, /ATTRS\{idVendor\}=="303a", ATTRS\{idProduct\}=="7002"/)
  assert.match(installer, /ATTRS\{idVendor\}=="1a86", ATTRS\{idProduct\}=="55d3"/)
  assert.match(installer, /SYMLINK\+="open-deskos-p4-camera"/)
  assert.match(installer, /SYMLINK\+="open-deskos-p4-debug"/)
  assert.match(sdkconfig, /CONFIG_TINYUSB_CDC_ENABLED=y/)
})

test('P4 native USB exposes CDC metadata and a standard 16 kHz mono UAC microphone', () => {
  const feature = fs.readFileSync(FEATURE_PATH, 'utf8')
  const manifest = fs.readFileSync(COMPONENT_MANIFEST_PATH, 'utf8')
  const cmake = fs.readFileSync(CMAKE_PATH, 'utf8')
  const kconfig = fs.readFileSync(KCONFIG_PATH, 'utf8')
  const sdkconfig = fs.readFileSync(SDKCONFIG_DEFAULTS_PATH, 'utf8')
  const main = fs.readFileSync(CAMERA_MAIN_PATH, 'utf8')

  assert.match(feature, /USB Audio Class microphone/)
  assert.match(feature, /OSPTEK ESP32-P4C6 module baseboard V1\.3 schematic/)
  assert.match(feature, /ADC output into P4 GPIO 11/)
  assert.match(feature, /signed 16-bit mono PCM at 16 kHz/)
  assert.match(manifest, /espressif\/usb_device_uac:/)
  assert.match(manifest, /espressif\/esp_codec_dev:/)
  assert.match(manifest, /espressif\/esp_video:\n    public: true\n    version: 2\.0\.1/)
  assert.match(cmake, /p4_usb_microphone\.c/)
  assert.match(kconfig, /config APP_USB_MICROPHONE/)
  assert.match(kconfig, /config APP_AUDIO_I2S_BCLK_PIN/)
  assert.match(kconfig, /config APP_AUDIO_I2S_WS_PIN/)
  assert.match(kconfig, /config APP_AUDIO_I2S_DIN_PIN/)
  assert.match(sdkconfig, /CONFIG_USB_DEVICE_UAC_AS_PART=y/)
  assert.match(sdkconfig, /CONFIG_UAC_MIC_CHANNEL_NUM=1/)
  assert.match(sdkconfig, /CONFIG_UAC_SAMPLE_RATE=16000/)
  assert.match(main, /p4_peripheral_i2c_init\(&peripheral_i2c\)/)
  assert.match(main, /p4_sc2336_init_hardware\(&pins, peripheral_i2c\)/)
  assert.match(main, /p4_usb_microphone_init\(peripheral_i2c\)/)
  assert.ok(fs.existsSync(AUDIO_HEADER_PATH), 'p4_usb_microphone.h must exist')
  assert.ok(fs.existsSync(AUDIO_SOURCE_PATH), 'p4_usb_microphone.c must exist')

  const audio = fs.readFileSync(AUDIO_SOURCE_PATH, 'utf8')
  assert.match(audio, /uac_device_init/)
  assert.match(audio, /\.skip_tinyusb_init = true/)
  assert.match(audio, /esp_codec_dev_read/)
  assert.match(audio, /\.sample_rate = 16000/)
  assert.match(audio, /\.channel = 1/)
  assert.match(audio, /\.bits_per_sample = 16/)
  assert.match(audio, /i2s_channel_enable/)
  assert.match(audio, /\.channel_mask = 0x01/)
  assert.match(audio, /audio I2S pins are not configured/)
  assert.match(audio, /Microphone self-test: samples=%u min=%d max=%d mean=%d ac_peak=%u ac_rms=%u clipped=%u/)
  assert.match(audio, /ac_peak >= 32 && ac_rms >= 8/)
  assert.match(audio, /clipped <= sample_count \/ 100/)
  assert.match(audio, /discard microphone startup samples/)
  assert.doesNotMatch(audio, /ESP_LOG[IE].*buffer/)
  assert.match(sdkconfig, /CONFIG_APP_AUDIO_I2S_MCLK_PIN=13/)
  assert.match(sdkconfig, /CONFIG_APP_AUDIO_I2S_BCLK_PIN=12/)
  assert.match(sdkconfig, /CONFIG_APP_AUDIO_I2S_WS_PIN=10/)
  assert.match(sdkconfig, /CONFIG_APP_AUDIO_I2S_DIN_PIN=11/)
})

test('CM5 P4 microphone acceptance validates live USB audio without storing speech', () => {
  assert.ok(fs.existsSync(HARDWARE_ACCEPTANCE_PATH), 'p4-microphone-acceptance.sh must exist')
  const script = fs.readFileSync(HARDWARE_ACCEPTANCE_PATH, 'utf8')
  assert.match(script, /lsusb -d "\$USB_ID"/)
  assert.match(script, /\/dev\/open-deskos-p4-camera/)
  assert.match(script, /ID_VENDOR_ID=303a/)
  assert.match(script, /ID_MODEL_ID=7002/)
  assert.match(script, /arecord -D "hw:\$CARD,\$DEVICE" -t raw -f S16_LE -r 16000 -c 1/)
  assert.match(script, /expected_bytes = int\(sys\.argv\[1\]\) \* 16000 \* 2/)
  assert.match(script, /python3 -c/)
  assert.match(script, /ac_rms/)
  assert.match(script, /clipped/)
  assert.doesNotMatch(script, />\s*\/tmp\/.*\.(wav|raw)/)
})

test('P4 camera C protocol headers define v1 metadata schema', () => {
  assert.ok(fs.existsSync(C_HEADER_PATH), 'p4_camera_protocol.h must exist')
  const header = fs.readFileSync(C_HEADER_PATH, 'utf8')
  assert.match(header, /P4_CAMERA_PROTOCOL_VERSION 1/)
  assert.match(header, /p4_camera_metadata_t/)
  assert.match(header, /p4_detected_face_t/)
  assert.match(header, /uint32_t sequence/)
  assert.match(header, /p4_camera_encode_metadata/)
  assert.match(header, /p4_camera_parse_metadata/)
})

test('P4 camera protocol parser rejects corrupt or unversioned frames', () => {
  assert.ok(fs.existsSync(C_SOURCE_PATH), 'p4_camera_protocol.c must exist')
  const source = fs.readFileSync(C_SOURCE_PATH, 'utf8')
  assert.match(source, /cJSON_GetObjectItemCaseSensitive\(root, "v"\)/)
  assert.match(source, /P4_CAMERA_PROTOCOL_VERSION/)
  assert.match(source, /cJSON_GetObjectItemCaseSensitive\(root, "online"\)/)
  assert.match(source, /cJSON_GetObjectItemCaseSensitive\(root, "faces_count"\)/)
})
