const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const REPOSITORY_ROOT = require('./helpers/repo-root').findRepositoryRoot(__dirname)
const CAMERA_ROOT = path.join(REPOSITORY_ROOT, 'peripherals', 'esp32-p4-camera')
const FEATURE_PATH = path.join(CAMERA_ROOT, 'tests', 'features', 'p4-camera.feature')
const README_PATH = path.join(CAMERA_ROOT, 'README.md')
const CAMERA_MAIN_PATH = path.join(CAMERA_ROOT, 'main', 'p4_camera_main.c')
const UVC_STREAM_SOURCE_PATH = path.join(CAMERA_ROOT, 'main', 'p4_uvc_stream.c')
const UVC_STREAM_HEADER_PATH = path.join(CAMERA_ROOT, 'main', 'p4_uvc_stream.h')
const INSTALL_PATH = path.join(__dirname, '..', 'scripts', 'cm5-install.sh')
const SDKCONFIG_DEFAULTS_PATH = path.join(CAMERA_ROOT, 'sdkconfig.defaults')
const KCONFIG_PATH = path.join(CAMERA_ROOT, 'main', 'Kconfig.projbuild')
const COMPONENT_MANIFEST_PATH = path.join(CAMERA_ROOT, 'main', 'idf_component.yml')
const CMAKE_PATH = path.join(CAMERA_ROOT, 'main', 'CMakeLists.txt')
const PARTITIONS_PATH = path.join(CAMERA_ROOT, 'partitions.csv')
const AUDIO_HEADER_PATH = path.join(CAMERA_ROOT, 'main', 'p4_usb_microphone.h')
const AUDIO_SOURCE_PATH = path.join(CAMERA_ROOT, 'main', 'p4_usb_microphone.c')
const USB_DESCRIPTORS_PATH = path.join(CAMERA_ROOT, 'main', 'usb_descriptors.c')
const TUSB_CONFIG_PATH = path.join(CAMERA_ROOT, 'main', 'tusb_config.h')
const MIC_ACCEPTANCE_PATH = path.join(__dirname, '..', 'scripts', 'p4-microphone-acceptance.sh')
const CAMERA_ACCEPTANCE_PATH = path.join(__dirname, '..', 'scripts', 'p4-camera-acceptance.sh')

test('P4 camera sub-device BDD feature defines generic UVC camera contract', () => {
  assert.ok(fs.existsSync(FEATURE_PATH), 'p4-camera.feature must exist')
  const feature = fs.readFileSync(FEATURE_PATH, 'utf8')
  assert.match(feature, /Feature: ESP32-P4 SC2336 generic UVC camera subsystem/)
  assert.match(feature, /SC2336 1080P CMOS image sensor/)
  assert.match(feature, /SDA GPIO 7 and SCL GPIO 8/)
  assert.match(feature, /GPIO 26/)
  assert.match(feature, /MIPI CSI-2/)
  assert.match(feature, /standard USB Video Class device/)
  assert.match(feature, /generic V4L2 video device/)
  assert.match(feature, /MJPEG frames at 1280x720/)
  assert.match(feature, /No on-device face or expression analysis exists/)
  assert.match(feature, /no face detection, no owner recognition, and no expression classification/)
  assert.match(feature, /No physical enrollment input exists/)
})

test('P4 camera sub-device README defines pinout and build commands', () => {
  assert.ok(fs.existsSync(README_PATH), 'README.md must exist')
  const readme = fs.readFileSync(README_PATH, 'utf8')
  assert.match(readme, /SC2336/)
  assert.match(readme, /ESP32-P4/)
  assert.match(readme, /GPIO 7/)
  assert.match(readme, /GPIO 8/)
  assert.match(readme, /GPIO 26/)
  assert.match(readme, /idf\.py set-target esp32p4/)
  assert.match(readme, /USB Video Class/)
  assert.match(readme, /no on-device face detection/i)
  assert.match(readme, /no model or biometric partitions/)
})

test('P4 firmware contains no face, expression, enrollment, or metadata code', () => {
  for (const missing of [
    'p4_face_inference.cpp',
    'p4_face_inference.h',
    'p4_expression_policy.c',
    'p4_expression_policy.h',
    'p4_camera_protocol.c',
    'p4_camera_protocol.h',
  ]) {
    assert.ok(!fs.existsSync(path.join(CAMERA_ROOT, 'main', missing)), `${missing} must be deleted`)
  }
  const main = fs.readFileSync(CAMERA_MAIN_PATH, 'utf8')
  assert.doesNotMatch(main, /p4_face_inference/)
  assert.doesNotMatch(main, /p4_camera_protocol/)
  assert.doesNotMatch(main, /p4_expression/)
  assert.doesNotMatch(main, /OWNER_CONFIRM/)
  assert.doesNotMatch(main, /cdcacm/)
  assert.doesNotMatch(main, /DIAGNOSTIC_SNAPSHOT/)
  assert.match(main, /p4_uvc_stream_init/)
  assert.match(main, /p4_uvc_stream_start/)
  assert.match(main, /p4_usb_microphone_init\(peripheral_i2c\)/)
  assert.match(main, /p4_sc2336_init_hardware\(&pins, peripheral_i2c\)/)
})

test('P4 firmware dependencies carry video and audio only', () => {
  const manifest = fs.readFileSync(COMPONENT_MANIFEST_PATH, 'utf8')
  const cmake = fs.readFileSync(CMAKE_PATH, 'utf8')
  assert.match(manifest, /espressif\/usb_device_uac:/)
  assert.match(manifest, /espressif\/esp_codec_dev:/)
  assert.match(manifest, /espressif\/esp_video:\n    public: true\n    version: 2\.0\.1/)
  assert.doesNotMatch(manifest, /human_face/)
  assert.doesNotMatch(manifest, /esp-dl/)
  assert.doesNotMatch(manifest, /cjson/)
  assert.match(cmake, /p4_uvc_stream\.c/)
  assert.match(cmake, /p4_usb_microphone\.c/)
  assert.doesNotMatch(cmake, /p4_face_inference/)
  assert.doesNotMatch(cmake, /p4_camera_protocol/)
  assert.doesNotMatch(cmake, /human_face/)
  assert.doesNotMatch(cmake, /cjson/)
})

test('P4 flash layout carries firmware only', () => {
  const partitions = fs.readFileSync(PARTITIONS_PATH, 'utf8')
  assert.match(partitions, /factory/)
  assert.doesNotMatch(partitions, /human_face/)
  assert.doesNotMatch(partitions, /storage/)
})

test('P4 UVC stream negotiates an encoder-compatible capture format', () => {
  assert.ok(fs.existsSync(UVC_STREAM_SOURCE_PATH), 'p4_uvc_stream.c must exist')
  assert.ok(fs.existsSync(UVC_STREAM_HEADER_PATH), 'p4_uvc_stream.h must exist')
  const header = fs.readFileSync(UVC_STREAM_HEADER_PATH, 'utf8')
  assert.match(header, /#define P4_UVC_WIDTH 1280/)
  assert.match(header, /#define P4_UVC_HEIGHT 720/)
  assert.match(header, /#define P4_UVC_FPS 30/)
  const source = fs.readFileSync(UVC_STREAM_SOURCE_PATH, 'utf8')
  assert.match(source, /ESP_VIDEO_JPEG_DEVICE_NAME/)
  assert.match(source, /V4L2_PIX_FMT_JPEG/)
  assert.match(source, /V4L2_PIX_FMT_RGB565/)
  assert.match(source, /V4L2_PIX_FMT_UYVY/)
  assert.match(source, /tud_video_n_frame_xfer/)
  assert.match(source, /tud_video_n_streaming/)
  assert.match(source, /usbd_edpt_busy/)
  assert.match(source, /P4_UVC_STAGE_SIZE/)
  assert.doesNotMatch(source, /transfer_index/)
  assert.match(source, /VIDIOC_S_EXT_CTRLS/)
  assert.match(source, /V4L2_CID_JPEG_COMPRESSION_QUALITY/)
})

test('P4 Kconfig exposes camera geometry and JPEG quality without recognition options', () => {
  const kconfig = fs.readFileSync(KCONFIG_PATH, 'utf8')
  const sdkconfig = fs.readFileSync(SDKCONFIG_DEFAULTS_PATH, 'utf8')
  assert.match(kconfig, /config APP_CAMERA_FRAME_WIDTH/)
  assert.match(kconfig, /config APP_UVC_JPEG_QUALITY/)
  assert.match(sdkconfig, /CONFIG_APP_CAMERA_FRAME_WIDTH=1280/)
  assert.match(sdkconfig, /CONFIG_APP_CAMERA_FRAME_HEIGHT=720/)
  assert.match(sdkconfig, /CONFIG_ESP_VIDEO_ENABLE_HW_JPEG_VIDEO_DEVICE=y/)
  assert.doesNotMatch(kconfig, /OWNER_CONFIRM/)
  assert.doesNotMatch(kconfig, /DIAGNOSTIC_SNAPSHOT/)
  assert.doesNotMatch(sdkconfig, /HUMAN_FACE/)
  assert.doesNotMatch(sdkconfig, /OWNER_CONFIRM/)
  assert.doesNotMatch(sdkconfig, /DIAGNOSTIC_SNAPSHOT/)
  assert.doesNotMatch(sdkconfig, /CONFIG_TINYUSB_CDC_ENABLED=y/)
})

test('P4 native composite USB identity matches the CM5 stable video rule', () => {
  const installer = fs.readFileSync(INSTALL_PATH, 'utf8')
  const descriptors = fs.readFileSync(USB_DESCRIPTORS_PATH, 'utf8')
  const tusb = fs.readFileSync(TUSB_CONFIG_PATH, 'utf8')
  assert.match(descriptors, /#define USB_VID 0x303A/)
  assert.match(descriptors, /#define USB_PID 0x7002/)
  assert.match(descriptors, /VIDEO_CS_ITF_VS_FORMAT_MJPEG/)
  assert.match(descriptors, /bAlternateSetting = 1/)
  assert.match(descriptors, /TUSB_XFER_ISOCHRONOUS/)
  assert.match(descriptors, /P4_UVC_WIDTH/)
  assert.doesNotMatch(descriptors, /CDC/)
  assert.doesNotMatch(descriptors, /cdcacm/i)
  assert.match(tusb, /CFG_TUD_VIDEO 1/)
  assert.match(tusb, /CFG_TUD_VIDEO_STREAMING_BULK 0/)
  assert.match(tusb, /CFG_TUD_VIDEO_STREAMING_EP_BUFSIZE 1024/)
  assert.match(installer, /ATTRS\{idVendor\}=="303a", ATTRS\{idProduct\}=="7002"/)
  assert.match(installer, /SUBSYSTEM=="video4linux", ATTR\{index\}=="0"/)
  assert.match(installer, /SYMLINK\+="open-deskos-p4-camera"/)
  assert.match(installer, /SYMLINK\+="open-deskos-p4-debug"/)
  assert.doesNotMatch(installer, /FACE_AGENT/)
  assert.doesNotMatch(installer, /face-agent/)
  assert.doesNotMatch(installer, /Face Agent/)
})

test('P4 native USB exposes a UVC camera and a standard 16 kHz mono UAC microphone', () => {
  const feature = fs.readFileSync(FEATURE_PATH, 'utf8')
  const manifest = fs.readFileSync(COMPONENT_MANIFEST_PATH, 'utf8')
  const cmake = fs.readFileSync(CMAKE_PATH, 'utf8')
  const kconfig = fs.readFileSync(KCONFIG_PATH, 'utf8')
  const sdkconfig = fs.readFileSync(SDKCONFIG_DEFAULTS_PATH, 'utf8')
  const main = fs.readFileSync(CAMERA_MAIN_PATH, 'utf8')

  assert.match(feature, /USB Audio Class microphone/)
  assert.match(feature, /OSPTEK ESP32-P4C6 module baseboard V1\.3 schematic/)
  assert.match(feature, /ADC output into P4 GPIO 11/)
  assert.match(feature, /signed 16-bit mono PCM at 16 kHz/)
  assert.match(manifest, /espressif\/usb_device_uac:/)
  assert.match(manifest, /espressif\/esp_codec_dev:/)
  assert.match(cmake, /p4_usb_microphone\.c/)
  assert.match(kconfig, /config APP_USB_MICROPHONE/)
  assert.match(kconfig, /config APP_AUDIO_I2S_BCLK_PIN/)
  assert.match(kconfig, /config APP_AUDIO_I2S_WS_PIN/)
  assert.match(kconfig, /config APP_AUDIO_I2S_DIN_PIN/)
  assert.match(sdkconfig, /CONFIG_USB_DEVICE_UAC_AS_PART=y/)
  assert.match(sdkconfig, /CONFIG_UAC_MIC_CHANNEL_NUM=1/)
  assert.match(sdkconfig, /CONFIG_UAC_SAMPLE_RATE=16000/)
  assert.match(main, /p4_peripheral_i2c_init\(&peripheral_i2c\)/)
  assert.match(main, /p4_sc2336_init_hardware\(&pins, peripheral_i2c\)/)
  assert.match(main, /p4_usb_microphone_init\(peripheral_i2c\)/)
  assert.ok(fs.existsSync(AUDIO_HEADER_PATH), 'p4_usb_microphone.h must exist')
  assert.ok(fs.existsSync(AUDIO_SOURCE_PATH), 'p4_usb_microphone.c must exist')

  const audio = fs.readFileSync(AUDIO_SOURCE_PATH, 'utf8')
  assert.match(audio, /uac_device_init/)
  assert.match(audio, /\.skip_tinyusb_init = true/)
  assert.match(audio, /esp_codec_dev_read/)
  assert.match(audio, /\.sample_rate = 16000/)
  assert.match(audio, /\.channel = 1/)
  assert.match(audio, /\.bits_per_sample = 16/)
  assert.match(audio, /i2s_channel_enable/)
  assert.match(audio, /\.channel_mask = 0x01/)
  assert.match(audio, /audio I2S pins are not configured/)
  assert.match(audio, /Microphone self-test: samples=%u min=%d max=%d mean=%d ac_peak=%u ac_rms=%u clipped=%u/)
  assert.match(audio, /ac_peak >= 32 && ac_rms >= 8/)
  assert.match(audio, /clipped <= sample_count \/ 100/)
  assert.match(audio, /discard microphone startup samples/)
  assert.doesNotMatch(audio, /ESP_LOG[IE].*buffer/)
  assert.match(sdkconfig, /CONFIG_APP_AUDIO_I2S_MCLK_PIN=13/)
  assert.match(sdkconfig, /CONFIG_APP_AUDIO_I2S_BCLK_PIN=12/)
  assert.match(sdkconfig, /CONFIG_APP_AUDIO_I2S_WS_PIN=10/)
  assert.match(sdkconfig, /CONFIG_APP_AUDIO_I2S_DIN_PIN=11/)
})

test('CM5 P4 microphone acceptance validates live USB audio without storing speech', () => {
  assert.ok(fs.existsSync(MIC_ACCEPTANCE_PATH), 'p4-microphone-acceptance.sh must exist')
  const script = fs.readFileSync(MIC_ACCEPTANCE_PATH, 'utf8')
  assert.match(script, /lsusb -d "\$USB_ID"/)
  assert.match(script, /arecord -D "hw:\$CARD,\$DEVICE" -t raw -f S16_LE -r 16000 -c 1/)
  assert.match(script, /expected_bytes = int\(sys\.argv\[1\]\) \* 16000 \* 2/)
  assert.match(script, /python3 -c/)
  assert.match(script, /ac_rms/)
  assert.match(script, /clipped/)
  assert.doesNotMatch(script, /CDC/)
  assert.doesNotMatch(script, />\s*\/tmp\/.*\.(wav|raw)/)
})

test('CM5 P4 camera acceptance validates a live UVC MJPEG frame without storing media', () => {
  assert.ok(fs.existsSync(CAMERA_ACCEPTANCE_PATH), 'p4-camera-acceptance.sh must exist')
  const script = fs.readFileSync(CAMERA_ACCEPTANCE_PATH, 'utf8')
  assert.match(script, /lsusb -d "\$USB_ID"/)
  assert.match(script, /resolve_video_device/)
  assert.match(script, /is_mjpg_node/)
  assert.match(script, /\/dev\/video\*/)
  assert.match(script, /ID_VENDOR_ID=303a/)
  assert.match(script, /ID_MODEL_ID=7002/)
  assert.match(script, /v4l2-ctl/)
  assert.match(script, /MJPG/)
  assert.match(script, /1280x720/)
  assert.match(script, /--stream-mmap/)
  assert.match(script, /--stream-to/)
  assert.match(script, /trap 'rm -f "\$FRAME_FILE"'/)
})
