const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const { privateReceipt } = require('./helpers/private-receipt')

test('receipt bytes are written only after protection, including repeated records', t => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'odk-receipt-')))
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const file = path.join(dir, 'receipt.json')
  const writer = privateReceipt(file, target => assert.equal(fs.readFileSync(target, 'utf8'), ''))
  writer.write('long private report'); writer.write('short'); writer.close()
  assert.equal(fs.readFileSync(file, 'utf8'), 'short')
  if (process.platform !== 'win32') assert.equal(fs.statSync(file).mode & 0o777, 0o600)
})

test('unsafe or unprotected receipts never receive failure bytes', t => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'odk-receipt-')))
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const file = path.join(dir, 'receipt.json')
  fs.writeFileSync(file, 'preserved')
  assert.throws(() => privateReceipt(file, () => { throw Error('ACL denied') }), /Private receipt unavailable/)
  assert.equal(fs.readFileSync(file, 'utf8'), 'preserved')
  const linked = path.join(dir, 'linked.json')
  fs.linkSync(file, linked)
  assert.throws(() => privateReceipt(linked, () => assert.fail('Must not protect a linked target')), /Private receipt unavailable/)
  assert.equal(fs.readFileSync(file, 'utf8'), 'preserved')
})

 test('symlink targets and replacement during protection remain untouched', t => {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'odk-receipt-')))
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }))
  const file = path.join(dir, 'receipt.json')
  const target = path.join(dir, 'target.json')
  fs.writeFileSync(target, 'preserved')
  fs.symlinkSync(target, file)
  assert.throws(() => privateReceipt(file, () => assert.fail('Must not protect a symlink')), /Private receipt unavailable/)
  fs.unlinkSync(file)
  fs.writeFileSync(file, '')
  assert.throws(() => privateReceipt(file, () => { fs.unlinkSync(file); fs.symlinkSync(target, file) }), /Private receipt unavailable/)
  assert.equal(fs.readFileSync(target, 'utf8'), 'preserved')
})
