#!/usr/bin/env python3
"""
tools/codegen_plugin_descriptor.py
Generates static C plugin descriptors (.rodata) from manifest.json for ESP-IDF firmware.
"""

import json
import os
import sys

KIND_MAP = {
    "device-driver": "ODK_KIND_DEVICE_DRIVER",
    "transport": "ODK_KIND_TRANSPORT",
    "processor": "ODK_KIND_PROCESSOR",
    "service": "ODK_KIND_SERVICE",
    "surface": "ODK_KIND_SURFACE",
    "protocol": "ODK_KIND_PROTOCOL",
}


def sanitize_ident(name):
    return name.replace(".", "_").replace("-", "_").replace("/", "_")


def generate_c_descriptors(manifest_paths, out_header, out_source):
    plugins = []
    for path in manifest_paths:
        with open(path, "r", encoding="utf-8") as f:
            plugins.append(json.load(f))

    # Generate Header
    with open(out_header, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by tools/codegen_plugin_descriptor.py - DO NOT EDIT */\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n#include \"esp_err.h\"\n\n")
        f.write("typedef enum {\n")
        f.write("    ODK_KIND_DEVICE_DRIVER,\n    ODK_KIND_TRANSPORT,\n    ODK_KIND_PROCESSOR,\n")
        f.write("    ODK_KIND_SERVICE,\n    ODK_KIND_SURFACE,\n    ODK_KIND_PROTOCOL,\n")
        f.write("} odk_plugin_kind_t;\n\n")
        f.write("typedef struct {\n    const char *interface_uri;\n    bool optional;\n} odk_port_desc_t;\n\n")
        f.write("typedef struct {\n")
        f.write("    esp_err_t (*init)(void *host_ctx, const void *config);\n")
        f.write("    esp_err_t (*start)(void);\n")
        f.write("    esp_err_t (*stop)(void);\n")
        f.write("    esp_err_t (*destroy)(void);\n")
        f.write("} odk_plugin_lifecycle_t;\n\n")
        f.write("typedef struct {\n")
        f.write("    const char *id;\n    const char *name;\n    uint32_t version;\n")
        f.write("    odk_plugin_kind_t kind;\n    const odk_plugin_lifecycle_t *lifecycle;\n")
        f.write("    size_t provides_count;\n    const odk_port_desc_t *provides;\n")
        f.write("    size_t requires_count;\n    const odk_port_desc_t *requires;\n")
        f.write("} odk_plugin_descriptor_t;\n\n")
        f.write(f"extern const odk_plugin_descriptor_t g_odk_plugins[{len(plugins)}];\n")
        f.write(f"extern const size_t g_odk_plugins_count;\n")

    # Generate Source
    with open(out_source, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by tools/codegen_plugin_descriptor.py - DO NOT EDIT */\n")
        f.write(f'#include "{os.path.basename(out_header)}"\n\n')

        for p in plugins:
            ident = sanitize_ident(p["id"])
            provides = p.get("provides", [])
            requires = p.get("requires", [])

            if provides:
                f.write(f"static const odk_port_desc_t s_provides_{ident}[] = {{\n")
                for port in provides:
                    uri = port.get("interface", "")
                    f.write(f'    {{ "{uri}", false }},\n')
                f.write("};\n\n")

            if requires:
                f.write(f"static const odk_port_desc_t s_requires_{ident}[] = {{\n")
                for port in requires:
                    uri = port.get("interface", "")
                    opt = "true" if port.get("optional") else "false"
                    f.write(f'    {{ "{uri}", {opt} }},\n')
                f.write("};\n\n")

        f.write(f"const odk_plugin_descriptor_t g_odk_plugins[{len(plugins)}] = {{\n")
        for p in plugins:
            ident = sanitize_ident(p["id"])
            kind = KIND_MAP.get(p.get("kind"), "ODK_KIND_SERVICE")
            provides = p.get("provides", [])
            requires = p.get("requires", [])

            prov_ptr = f"s_provides_{ident}" if provides else "NULL"
            req_ptr = f"s_requires_{ident}" if requires else "NULL"

            f.write("    {\n")
            f.write(f'        .id = "{p["id"]}",\n')
            f.write(f'        .name = "{p.get("name", p["id"])}",\n')
            f.write(f"        .version = 1,\n")
            f.write(f"        .kind = {kind},\n")
            f.write("        .lifecycle = NULL,\n")
            f.write(f"        .provides_count = {len(provides)},\n")
            f.write(f"        .provides = {prov_ptr},\n")
            f.write(f"        .requires_count = {len(requires)},\n")
            f.write(f"        .requires = {req_ptr},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write(f"const size_t g_odk_plugins_count = {len(plugins)};\n")


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: codegen_plugin_descriptor.py <out_header> <out_source> <manifest1.json> [manifest2.json...]")
        sys.exit(1)
    generate_c_descriptors(sys.argv[3:], sys.argv[1], sys.argv[2])
